#!/usr/bin/env python3
"""Bake a TTF font into a C header so the demo needs no external asset files.

The demo loads its UI font at runtime. To make the binary fully self-contained
(no `assets/` directory required next to the exe, no preloaded web filesystem),
this script converts the TTF into a byte array in a generated header that
`main.cpp` includes and hands to raylib's `LoadFontFromMemory`.

Usage:
    python embed_font.py                    # regenerate embedded_font.h from Roboto
    python embed_font.py --font path.ttf --out embedded_font.h --symbol kEmbeddedFont

The generated header is committed so the project builds with just a C++
compiler (no codegen step needed). Re-run this only when the source font
changes.
"""

from __future__ import annotations

import argparse
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent


def emit_header(data: bytes, symbol: str, source_name: str) -> str:
    lines = [
        "// Generated by embed_font.py - do not edit by hand.",
        f"// Source: {source_name} ({len(data)} bytes)",
        "//",
        "// The demo's UI font, baked into the binary so no external asset files",
        "// are needed at runtime. Fed to raylib's LoadFontFromMemory(\".ttf\", ...).",
        "#pragma once",
        "",
        f"static const unsigned int {symbol}Size = {len(data)}u;",
        f"static const unsigned char {symbol}[] = {{",
    ]
    # 16 bytes per line keeps the file readable and compilers happy.
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--font",
        default=str(PROJECT_ROOT / "assets" / "fonts" / "Roboto-Regular.ttf"),
        help="source TTF file (default: assets/fonts/Roboto-Regular.ttf)",
    )
    parser.add_argument(
        "--out",
        default=str(PROJECT_ROOT / "embedded_font.h"),
        help="output header path (default: embedded_font.h)",
    )
    parser.add_argument(
        "--symbol",
        default="kEmbeddedRobotoTTF",
        help="C identifier for the byte array (default: kEmbeddedRobotoTTF)",
    )
    args = parser.parse_args()

    font_path = Path(args.font)
    if not font_path.exists():
        raise SystemExit(f"error: font not found: {font_path}")

    data = font_path.read_bytes()
    header = emit_header(data, args.symbol, font_path.name)
    out_path = Path(args.out)
    out_path.write_text(header, encoding="ascii")
    print(f"wrote {out_path} ({len(data)} bytes of font -> {out_path.stat().st_size} bytes of C)")


if __name__ == "__main__":
    main()
