// clay-widgets demo application.
//
// Structured like a small real program rather than a widget dump:
//   - Dashboard: live task statistics, a data table, and quick actions.
//   - Tasks:     a working to-do manager (add / edit / filter / delete) built
//                from the kit's list rows, inputs, radios and modal dialog.
//   - Gallery:   the full widget catalog, grouped into themed cards.
//   - Settings:  theme presets, behavior toggles and live diagnostics.
//
// All state lives in DemoState (plain structs, rebuilt into UI every frame);
// rendering is raylib; the same file compiles to desktop and WebAssembly.

#include <algorithm>
#include <cmath>
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <utility>
#include <vector>

#define CLAY_IMPLEMENTATION
#include "clay.h"

#define CLAY_WIDGETS_IMPLEMENTATION
#include "clay-widgets/widgets.h"

#include "raylib.h"

// UI font baked into the binary (generated by embed_font.py) so the demo runs
// with no external asset files - see the font setup in main().
#include "embedded_font.h"

// Gamma-correct the text atlas so anti-aliased edges aren't composited too light
// (raylib blends coverage in sRGB space, which makes text read thin - worst on
// the dark themes). CPU-side, not a shader, so it also works on web. Comment out
// the define to disable, or tune the curve with e.g. -DCLAY_WIDGETS_TEXT_GAMMA=2.2f.
#define CLAY_WIDGETS_TEXT_GAMMA_CORRECTION
#include "text_gamma.h"

#ifdef __EMSCRIPTEN__
#include <emscripten/emscripten.h>
#include <emscripten/html5.h>
#include <functional>
#endif

namespace {

#ifdef __EMSCRIPTEN__
// The browser owns the frame loop, so on web we hand a per-frame callback to
// emscripten instead of spinning our own while() loop. The callback captures
// main()'s locals by reference; compiling with -sASYNCIFY and
// simulate_infinite_loop=1 keeps main()'s stack (and therefore those locals)
// alive for the lifetime of the page.
static std::function<void()> g_webFrame;
static void ClayWidgets_WebFrame() {
    if (g_webFrame) {
        g_webFrame();
    }
}

// Resize the raylib window (and thus the canvas) to match the browser window.
// raylib reads GetScreenWidth()/GetScreenHeight() every frame, so this is all
// the Clay layout needs to reflow responsively. Emscripten's GLFW handles the
// HiDPI backing-store scaling, so text stays crisp.
static void ClayWidgets_SyncCanvasToWindow() {
    int w = EM_ASM_INT({ return window.innerWidth; });
    int h = EM_ASM_INT({ return window.innerHeight; });
    if (w > 0 && h > 0) {
        SetWindowSize(w, h);
    }
}

static EM_BOOL ClayWidgets_OnResize(int, const EmscriptenUiEvent *e, void *) {
    if (e && e->windowInnerWidth > 0 && e->windowInnerHeight > 0) {
        SetWindowSize(e->windowInnerWidth, e->windowInnerHeight);
    } else {
        ClayWidgets_SyncCanvasToWindow();
    }
    return EM_FALSE;
}
#endif

static Clay_String ClayStringFromCString(const char *text) {
    Clay_String s = {};
    if (!text) {
        s.chars = "";
        s.length = 0;
        s.isStaticallyAllocated = true;
        return s;
    }
    s.chars = text;
    s.length = static_cast<int32_t>(std::strlen(text));
    s.isStaticallyAllocated = false;
    return s;
}

static Color ToRaylibColor(Clay_Color c) {
    auto clampByte = [](float v) -> unsigned char {
        if (v < 0.0f) return 0;
        if (v > 255.0f) return 255;
        return static_cast<unsigned char>(std::round(v));
    };
    return Color{clampByte(c.r), clampByte(c.g), clampByte(c.b), clampByte(c.a)};
}

static Color MixOverlay(Color base, Color overlay) {
    float a = static_cast<float>(overlay.a) / 255.0f;
    Color out = {
        static_cast<unsigned char>(base.r + (overlay.r - base.r) * a),
        static_cast<unsigned char>(base.g + (overlay.g - base.g) * a),
        static_cast<unsigned char>(base.b + (overlay.b - base.b) * a),
        base.a,
    };
    return out;
}

static void AppendUtf8FromCodepoint(char *buffer, int &length, int maxLength, int codepoint) {
    if (maxLength <= 0 || length >= maxLength) {
        return;
    }

    auto pushByte = [&](unsigned char b) {
        if (length < maxLength) {
            buffer[length++] = static_cast<char>(b);
        }
    };

    if (codepoint <= 0x7F) {
        pushByte(static_cast<unsigned char>(codepoint));
        return;
    }
    if (codepoint <= 0x7FF) {
        pushByte(static_cast<unsigned char>(0xC0 | ((codepoint >> 6) & 0x1F)));
        pushByte(static_cast<unsigned char>(0x80 | (codepoint & 0x3F)));
        return;
    }
    if (codepoint <= 0xFFFF) {
        pushByte(static_cast<unsigned char>(0xE0 | ((codepoint >> 12) & 0x0F)));
        pushByte(static_cast<unsigned char>(0x80 | ((codepoint >> 6) & 0x3F)));
        pushByte(static_cast<unsigned char>(0x80 | (codepoint & 0x3F)));
        return;
    }
    pushByte(static_cast<unsigned char>(0xF0 | ((codepoint >> 18) & 0x07)));
    pushByte(static_cast<unsigned char>(0x80 | ((codepoint >> 12) & 0x3F)));
    pushByte(static_cast<unsigned char>(0x80 | ((codepoint >> 6) & 0x3F)));
    pushByte(static_cast<unsigned char>(0x80 | (codepoint & 0x3F)));
}

// A raylib Font bakes every glyph into one texture at a single pixel size; then
// DrawTextEx scales that bitmap to whatever size you draw - and scaling a baked
// bitmap is what softens text. FontCache instead bakes one atlas per pixel size
// the UI actually asks for, lazily, so every glyph is drawn ~1:1. The kit uses
// only a handful of sizes (13/14/16/18/24/30), so the cache stays tiny.
//
// Sizes are keyed in *physical* pixels: raylib's HighDPI path scales every draw
// by GetWindowScaleDPI(), so a glyph drawn at logical size S covers S*dpi device
// pixels. Baking at round(S*dpi) and drawing with the logical size S makes the
// atlas sample 1:1 on screen at any DPI; measurement stays in logical units
// because MeasureTextEx divides the same factor back out.
struct FontCache {
    float dpiScale = 1.0f;
    Font fallback = {};                        // used if the embedded font failed
    bool haveEmbedded = false;
    std::vector<std::pair<int, Font>> atlases; // physical pixel size -> baked Font
};

// Maps a logical font size to the physical pixel size we bake at (min 1).
static int FontCache_PixelSize(const FontCache &cache, float logicalSize) {
    int px = static_cast<int>(std::lround(logicalSize * cache.dpiScale));
    return px < 1 ? 1 : px;
}

// Returns the atlas baked at pixelSize, baking and caching it on first use.
// Never returns null: falls back to the default font if the embedded font is
// unavailable or a bake fails.
static Font *FontCache_Get(FontCache &cache, int pixelSize) {
    if (!cache.haveEmbedded) {
        return &cache.fallback;
    }
    for (auto &entry : cache.atlases) {
        if (entry.first == pixelSize) {
            return &entry.second;
        }
    }
    Font baked = ClayWidgets_BakeFont(kEmbeddedRobotoTTF, static_cast<int>(kEmbeddedRobotoTTFSize), pixelSize);
    if (baked.texture.id == 0) {
        return &cache.fallback;
    }
    SetTextureFilter(baked.texture, TEXTURE_FILTER_BILINEAR);
    cache.atlases.emplace_back(pixelSize, baked);
    return &cache.atlases.back().second;
}

static void FontCache_Unload(FontCache &cache) {
    for (auto &entry : cache.atlases) {
        UnloadFont(entry.second);
    }
    cache.atlases.clear();
    cache.haveEmbedded = false;
}

static Clay_Dimensions MeasureTextRaylib(Clay_StringSlice text, Clay_TextElementConfig *config, void *userData) {
    FontCache *cache = static_cast<FontCache *>(userData);
    float fontSize = static_cast<float>(config->fontSize);
    Font font = cache ? *FontCache_Get(*cache, FontCache_PixelSize(*cache, fontSize))
                      : GetFontDefault();

    std::string tmp;
    tmp.assign(text.chars, text.length);

    float spacing = static_cast<float>(config->letterSpacing);
    Vector2 measured = MeasureTextEx(font, tmp.c_str(), fontSize, spacing);

    Clay_Dimensions out = {};
    out.width = measured.x;
    out.height = measured.y;
    return out;
}

static void HandleClayError(Clay_ErrorData errorData) {
    std::string msg(errorData.errorText.chars, errorData.errorText.length);
    TraceLog(LOG_ERROR, "Clay error (%d): %s", static_cast<int>(errorData.errorType), msg.c_str());
}

static Rectangle IntersectRects(Rectangle a, Rectangle b) {
    float x1 = std::max(a.x, b.x);
    float y1 = std::max(a.y, b.y);
    float x2 = std::min(a.x + a.width, b.x + b.width);
    float y2 = std::min(a.y + a.height, b.y + b.height);
    if (x2 < x1 || y2 < y1) {
        return Rectangle{x1, y1, 0, 0};
    }
    return Rectangle{x1, y1, x2 - x1, y2 - y1};
}

// Raylib's DrawRectangleRounded applies one radius to all four corners, so
// mixed-radius fills (e.g. the end cells of a segmented control, which round
// only their outer corners) are assembled from quarter-disc sectors plus
// non-overlapping horizontal strips - overlap would double-blend translucent
// fills.
static void DrawRectangleRoundedPerCorner(Rectangle rect, Clay_CornerRadius cr, int segments, Color color) {
    float maxRadius = 0.5f * std::min(rect.width, rect.height);
    float tl = std::min(cr.topLeft, maxRadius);
    float tr = std::min(cr.topRight, maxRadius);
    float bl = std::min(cr.bottomLeft, maxRadius);
    float br = std::min(cr.bottomRight, maxRadius);

    if (tl == tr && tl == bl && tl == br) {
        float minDim = std::max(1.0f, std::min(rect.width, rect.height));
        float roundness = std::min(1.0f, 2.0f * tl / minDim);
        DrawRectangleRounded(rect, roundness, segments, color);
        return;
    }

    if (tl > 0.0f) DrawCircleSector(Vector2{rect.x + tl, rect.y + tl}, tl, 180.0f, 270.0f, segments, color);
    if (tr > 0.0f) DrawCircleSector(Vector2{rect.x + rect.width - tr, rect.y + tr}, tr, 270.0f, 360.0f, segments, color);
    if (br > 0.0f) DrawCircleSector(Vector2{rect.x + rect.width - br, rect.y + rect.height - br}, br, 0.0f, 90.0f, segments, color);
    if (bl > 0.0f) DrawCircleSector(Vector2{rect.x + bl, rect.y + rect.height - bl}, bl, 90.0f, 180.0f, segments, color);

    // The rest is the rect minus the four corner squares: split it at every
    // corner-square edge into horizontal strips, insetting each strip past
    // whichever corner squares it runs alongside.
    float ys[6] = {0.0f, tl, tr, rect.height - bl, rect.height - br, rect.height};
    std::sort(ys, ys + 6);
    for (int s = 0; s < 5; ++s) {
        float y1 = ys[s];
        float y2 = ys[s + 1];
        if (y2 - y1 <= 0.0f) {
            continue;
        }
        float mid = 0.5f * (y1 + y2);
        float left = (mid < tl) ? tl : ((mid > rect.height - bl) ? bl : 0.0f);
        float right = (mid < tr) ? tr : ((mid > rect.height - br) ? br : 0.0f);
        DrawRectangleRec(Rectangle{rect.x + left, rect.y + y1, rect.width - left - right, y2 - y1}, color);
    }
}

static void RenderClayCommands(Clay_RenderCommandArray commands, FontCache &fontCache) {
    std::vector<Rectangle> scissorStack;
    std::vector<Color> overlayStack;
    bool scissorEnabled = false;
    const int roundedCornerSegments = 24;

    auto reapplyScissor = [&]() {
        if (scissorEnabled) {
            EndScissorMode();
            scissorEnabled = false;
        }
        if (!scissorStack.empty()) {
            Rectangle r = scissorStack.back();
            BeginScissorMode(static_cast<int>(r.x), static_cast<int>(r.y), static_cast<int>(r.width), static_cast<int>(r.height));
            scissorEnabled = true;
        }
    };

    auto applyOverlay = [&](Color c) -> Color {
        Color out = c;
        for (Color overlay : overlayStack) {
            out = MixOverlay(out, overlay);
        }
        return out;
    };

    for (int i = 0; i < commands.length; ++i) {
        Clay_RenderCommand *cmd = Clay_RenderCommandArray_Get(&commands, i);
        // Snap boxes to whole pixels. Clay lays out in floats, so sibling
        // edges land on fractional coordinates and rasterize as a half-pixel
        // blur that reads as uneven widths and gaps (three equally-grown
        // cards can each look a different size). Rounding the two edges
        // independently (rather than x and width) keeps adjacent elements
        // flush with each other.
        float x0 = std::round(cmd->boundingBox.x);
        float y0 = std::round(cmd->boundingBox.y);
        Rectangle rect = {
            x0,
            y0,
            std::round(cmd->boundingBox.x + cmd->boundingBox.width) - x0,
            std::round(cmd->boundingBox.y + cmd->boundingBox.height) - y0,
        };

        switch (cmd->commandType) {
            case CLAY_RENDER_COMMAND_TYPE_RECTANGLE: {
                Color color = applyOverlay(ToRaylibColor(cmd->renderData.rectangle.backgroundColor));
                DrawRectangleRoundedPerCorner(rect, cmd->renderData.rectangle.cornerRadius, roundedCornerSegments, color);
                break;
            }
            case CLAY_RENDER_COMMAND_TYPE_TEXT: {
                const Clay_TextRenderData &text = cmd->renderData.text;
                Font font = *FontCache_Get(fontCache, FontCache_PixelSize(fontCache, static_cast<float>(text.fontSize)));
                std::string tmp(text.stringContents.chars, text.stringContents.length);
                Color color = applyOverlay(ToRaylibColor(text.textColor));
                DrawTextEx(font, tmp.c_str(), Vector2{rect.x, rect.y}, static_cast<float>(text.fontSize), static_cast<float>(text.letterSpacing), color);
                break;
            }
            case CLAY_RENDER_COMMAND_TYPE_BORDER: {
                const Clay_BorderRenderData &b = cmd->renderData.border;
                Color c = applyOverlay(ToRaylibColor(b.color));
                float radius = b.cornerRadius.topLeft;
                bool uniformWidth = b.width.left == b.width.right
                    && b.width.top == b.width.bottom
                    && b.width.left == b.width.top;
                if (radius > 0.0f && uniformWidth && b.width.left > 0) {
                    // Draw a rounded, inset border whose outer edge aligns with the
                    // element's rounded background so fills never appear to bleed past it.
                    float t = static_cast<float>(b.width.left);
                    Rectangle inner = { rect.x + t, rect.y + t, rect.width - 2.0f * t, rect.height - 2.0f * t };
                    float minDim = std::min(inner.width, inner.height);
                    float innerRadius = std::max(0.0f, radius - t);
                    float roundness = minDim > 0.0f ? std::min(1.0f, 2.0f * innerRadius / minDim) : 0.0f;
                    DrawRectangleRoundedLinesEx(inner, roundness, roundedCornerSegments, t, c);
                } else {
                    if (b.width.top > 0) DrawRectangle(static_cast<int>(rect.x), static_cast<int>(rect.y), static_cast<int>(rect.width), b.width.top, c);
                    if (b.width.bottom > 0) DrawRectangle(static_cast<int>(rect.x), static_cast<int>(rect.y + rect.height - b.width.bottom), static_cast<int>(rect.width), b.width.bottom, c);
                    if (b.width.left > 0) DrawRectangle(static_cast<int>(rect.x), static_cast<int>(rect.y), b.width.left, static_cast<int>(rect.height), c);
                    if (b.width.right > 0) DrawRectangle(static_cast<int>(rect.x + rect.width - b.width.right), static_cast<int>(rect.y), b.width.right, static_cast<int>(rect.height), c);
                }
                break;
            }
            case CLAY_RENDER_COMMAND_TYPE_SCISSOR_START: {
                if (scissorStack.empty()) {
                    scissorStack.push_back(rect);
                } else {
                    scissorStack.push_back(IntersectRects(scissorStack.back(), rect));
                }
                reapplyScissor();
                break;
            }
            case CLAY_RENDER_COMMAND_TYPE_SCISSOR_END: {
                if (!scissorStack.empty()) {
                    scissorStack.pop_back();
                }
                reapplyScissor();
                break;
            }
            case CLAY_RENDER_COMMAND_TYPE_OVERLAY_COLOR_START: {
                overlayStack.push_back(ToRaylibColor(cmd->renderData.overlayColor.color));
                break;
            }
            case CLAY_RENDER_COMMAND_TYPE_OVERLAY_COLOR_END: {
                if (!overlayStack.empty()) {
                    overlayStack.pop_back();
                }
                break;
            }
            case CLAY_RENDER_COMMAND_TYPE_IMAGE: {
                const Clay_ImageRenderData &img = cmd->renderData.image;
                if (img.imageData) {
                    Texture2D *tex = static_cast<Texture2D *>(img.imageData);
                    // The widget layer packs an optional 0xRRGGBBAA tint into
                    // userData (see clay-widgets/image.h). A null/zero value
                    // means untinted, so we draw the texture as-is (WHITE).
                    Color tint = WHITE;
                    if (cmd->userData) {
                        tint = ToRaylibColor(ClayWidgets_UnpackTint(cmd->userData));
                    }
                    tint = applyOverlay(tint);
                    Rectangle src = {0.0f, 0.0f, static_cast<float>(tex->width), static_cast<float>(tex->height)};
                    DrawTexturePro(*tex, src, rect, Vector2{0.0f, 0.0f}, 0.0f, tint);
                }
                break;
            }
            case CLAY_RENDER_COMMAND_TYPE_CUSTOM:
            case CLAY_RENDER_COMMAND_TYPE_NONE:
            default:
                break;
        }
    }

    if (scissorEnabled) {
        EndScissorMode();
    }
}

// ---------------------------------------------------------------------------
// Demo data and state
// ---------------------------------------------------------------------------

enum DemoView {
    kViewDashboard = 0,
    kViewTasks = 1,
    kViewGallery = 2,
    kViewSettings = 3,
};

constexpr int32_t kMaxTasks = 32;
constexpr int32_t kTaskTitleCap = 64;

// Priorities are indexes into these tables: 0 = High, 1 = Medium, 2 = Low.
static const Clay_String kPriorityNames[] = {
    CLAY_STRING("High"),
    CLAY_STRING("Medium"),
    CLAY_STRING("Low"),
};
static const Clay_Color kPrioritySwatches[] = {
    Clay_Color{224, 82, 64, 255},
    Clay_Color{240, 180, 60, 255},
    Clay_Color{110, 168, 224, 255},
};

static const Clay_String kTaskFilterNames[] = {
    CLAY_STRING("All"),
    CLAY_STRING("Active"),
    CLAY_STRING("Done"),
};

static const Clay_String kThemeNames[] = {
    CLAY_STRING("Slate"),
    CLAY_STRING("Sand"),
    CLAY_STRING("Forest"),
    CLAY_STRING("Win95"),
};

static const Clay_String kDensityNames[] = {
    CLAY_STRING("Compact"),
    CLAY_STRING("Cozy"),
    CLAY_STRING("Comfortable"),
};

static const Clay_String kChannelNames[] = {
    CLAY_STRING("Stable"),
    CLAY_STRING("Beta"),
    CLAY_STRING("Nightly"),
    CLAY_STRING("Canary"),
};

static const Clay_String kLogLevelNames[] = {
    CLAY_STRING("Error"),
    CLAY_STRING("Warning"),
    CLAY_STRING("Info"),
    CLAY_STRING("Debug"),
    CLAY_STRING("Trace"),
};

static const Clay_String kBuildConfigNames[] = {
    CLAY_STRING("Debug"),
    CLAY_STRING("Release"),
    CLAY_STRING("Release with Debug Info"),
    CLAY_STRING("Minimum Size"),
};

// Rows for the Dashboard "Recent builds" table.
static const Clay_String kBuildNames[] = {
    CLAY_STRING("web build"),
    CLAY_STRING("widget sweep"),
    CLAY_STRING("theme audit"),
    CLAY_STRING("wasm smoke test"),
};
static const Clay_String kBuildStates[] = {
    CLAY_STRING("passing"),
    CLAY_STRING("passing"),
    CLAY_STRING("flaky"),
    CLAY_STRING("broken"),
};
static const Clay_String kBuildTimes[] = {
    CLAY_STRING("2m 14s"),
    CLAY_STRING("1m 03s"),
    CLAY_STRING("4m 41s"),
    CLAY_STRING("0m 12s"),
};
constexpr int32_t kBuildRowCount = 4;

// Pages for the Gallery's attached-tab mini plane.
struct MiniTabPage {
    Clay_String label;
    Clay_String body;
};
static const MiniTabPage kMiniTabs[] = {
    {
        CLAY_STRING("Overview"),
        CLAY_STRING("Attached tabs share one framed surface with the panel below, so the strip and body read as a single control."),
    },
    {
        CLAY_STRING("Behavior"),
        CLAY_STRING("Each tab is a radio bound to one shared integer. Rebuild the body from that integer every frame and the panel swaps for free."),
    },
    {
        CLAY_STRING("Keyboard"),
        CLAY_STRING("Tabs join the global focus order: Tab reaches the strip and Enter activates the focused tab."),
    },
};
constexpr int32_t kMiniTabCount = static_cast<int32_t>(sizeof(kMiniTabs) / sizeof(kMiniTabs[0]));

struct DemoTask {
    char title[kTaskTitleCap];
    int32_t priority; // index into kPriorityNames
    bool done;
};

struct DemoSeedTask {
    const char *title;
    int32_t priority;
    bool done;
};
static const DemoSeedTask kSeedTasks[] = {
    {"Ship the 0.2 release notes", 0, false},
    {"Fix wheel scroll over clipped tables", 0, true},
    {"Add the selectable list-row widget", 1, true},
    {"Document the theme presets", 1, false},
    {"Profile text measurement on web", 2, false},
    {"Run the wasm smoke test", 2, false},
    {"Refactor focus-ring drawing", 1, false},
    {"Design a date-picker widget", 2, false},
};

constexpr int32_t kScratchSlots = 24;
constexpr int32_t kScratchBytes = 128;

struct DemoState {
    int32_t activeView = kViewDashboard;

    // Tasks
    DemoTask tasks[kMaxTasks] = {};
    int32_t taskCount = 0;
    int32_t selectedTask = 0;
    int32_t taskFilter = 0; // index into kTaskFilterNames
    char newTaskTitle[kTaskTitleCap] = "";
    int32_t newTaskPriority = 1;
    int32_t contextTask = -1; // task the context menu was opened on

    // Structural task edits (delete / clear / reset) are deferred to the top of
    // the next frame: applying them mid-layout would move task memory that
    // Clay_Strings declared earlier this frame still point into.
    int32_t pendingDelete = -1;
    bool pendingClearCompleted = false;
    bool pendingReset = false;

    // Delete confirmation modal
    bool showDeleteModal = false;
    int32_t deleteTarget = -1; // -1 falls back to the selected task

    // Dashboard
    int32_t selectedBuild = 1;

    // Gallery
    int32_t galleryClicks = 0;
    bool autosave = true;
    bool telemetryLocked = true; // shown via a disabled checkbox
    int32_t quality = 2;         // radio values 1..3
    float volume = 0.4f;
    int32_t density = 1;
    int32_t retryCount = 3;
    char galleryText[128] = "";
    int32_t buildConfig = 1;
    int32_t channel = 0;
    bool treeSrcOpen = true;
    bool treeWidgetsOpen = true;
    bool treeAssetsOpen = false;
    int32_t miniTab = 0;

    // Settings
    int32_t themePreset = CLAY_WIDGETS_THEME_PRESET_SLATE;
    bool animationsOn = true;
    bool notifications = true;
    bool verboseLogging = false;
    bool experimentalGpu = false;
    bool showAdvanced = false;
    int32_t logLevel = 2;

    // Status bar
    char statusLine[128] = "Ready";

    // Per-frame scratch for formatted labels. Clay retains Clay_String pointers
    // until render, so these live here (reset each frame) instead of on an
    // inner scope's stack that closes before the frame is drawn.
    char scratch[kScratchSlots][kScratchBytes] = {};
    int32_t scratchUsed = 0;
};

// Textures for the tintable-icon demo, generated procedurally at startup.
struct DemoIcons {
    Texture2D check;
    Texture2D play;
    Texture2D circle;
    Texture2D square;
};

static void SetStatus(DemoState &s, const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    std::vsnprintf(s.statusLine, sizeof(s.statusLine), fmt, ap);
    va_end(ap);
}

// Formats into the per-frame scratch ring and returns a Clay_String view of it.
static Clay_String FormatString(DemoState &s, const char *fmt, ...) {
    char *buf = s.scratch[s.scratchUsed % kScratchSlots];
    s.scratchUsed++;

    va_list ap;
    va_start(ap, fmt);
    int n = std::vsnprintf(buf, kScratchBytes, fmt, ap);
    va_end(ap);
    if (n < 0) {
        n = 0;
    }
    if (n > kScratchBytes - 1) {
        n = kScratchBytes - 1;
    }

    Clay_String out = {};
    out.isStaticallyAllocated = false;
    out.length = n;
    out.chars = buf;
    return out;
}

// Small dim caption. The kit only ships Label, so this drops down to a raw
// CLAY_TEXT - which is also how apps are expected to extend the kit.
static void MutedLabel(ClayWidgets_Context &ui, Clay_String text) {
    CLAY_TEXT(text, {
        .textColor = ui.theme.textMutedColor,
        .fontId = ui.theme.fontBody,
        .fontSize = ui.theme.fontSizeSmall,
    });
}

// All demo toasts route through here so the Settings "notifications" toggle
// actually governs app behavior.
static void Notify(ClayWidgets_Context &ui, DemoState &s, Clay_String message, ClayWidgets_BadgeVariant variant, float seconds) {
    if (s.notifications) {
        ClayWidgets_ShowToast(&ui, message, variant, seconds);
    }
}

// Appends a task. Appending never moves existing entries in the fixed array,
// so it is safe to call mid-layout (unlike delete, which is deferred).
static bool AddTask(DemoState &s, const char *title, int32_t priority) {
    if (!title || !title[0] || s.taskCount >= kMaxTasks) {
        return false;
    }
    DemoTask &t = s.tasks[s.taskCount++];
    std::snprintf(t.title, sizeof(t.title), "%s", title);
    t.priority = priority < 0 ? 0 : (priority > 2 ? 2 : priority);
    t.done = false;
    return true;
}

static void SeedTasks(DemoState &s) {
    s.taskCount = 0;
    for (const DemoSeedTask &seed : kSeedTasks) {
        if (AddTask(s, seed.title, seed.priority)) {
            s.tasks[s.taskCount - 1].done = seed.done;
        }
    }
}

static void ResetDemoState(DemoState &s) {
    int32_t view = s.activeView;
    s = DemoState{};
    s.activeView = view;
    SeedTasks(s);
    SetStatus(s, "Demo state reset");
}

// Applies deferred structural edits. Runs at the top of each frame, before any
// layout is declared, so no live Clay_String can point into moved task memory.
static void ApplyPendingTaskEdits(DemoState &s) {
    if (s.pendingReset) {
        ResetDemoState(s);
        return;
    }
    if (s.pendingClearCompleted) {
        s.pendingClearCompleted = false;
        int32_t kept = 0;
        for (int32_t i = 0; i < s.taskCount; ++i) {
            if (!s.tasks[i].done) {
                s.tasks[kept++] = s.tasks[i];
            }
        }
        s.taskCount = kept;
    }
    if (s.pendingDelete >= 0) {
        if (s.pendingDelete < s.taskCount) {
            for (int32_t i = s.pendingDelete; i + 1 < s.taskCount; ++i) {
                s.tasks[i] = s.tasks[i + 1];
            }
            --s.taskCount;
        }
        s.pendingDelete = -1;
    }
    if (s.selectedTask >= s.taskCount) {
        s.selectedTask = s.taskCount - 1;
    }
    if (s.selectedTask < 0) {
        s.selectedTask = 0;
    }
    if (s.contextTask >= s.taskCount) {
        s.contextTask = -1;
    }
    if (s.deleteTarget >= s.taskCount) {
        s.deleteTarget = -1;
    }
}

static int32_t CountCompletedTasks(const DemoState &s) {
    int32_t done = 0;
    for (int32_t i = 0; i < s.taskCount; ++i) {
        if (s.tasks[i].done) {
            ++done;
        }
    }
    return done;
}

static void AddSampleTask(ClayWidgets_Context &ui, DemoState &s) {
    if (AddTask(s, "Explore the Tasks view", 1)) {
        s.selectedTask = s.taskCount - 1;
        SetStatus(s, "Added a sample task");
        Notify(ui, s, CLAY_STRING("Task added"), CLAY_WIDGETS_BADGE_SUCCESS, 2.5f);
    } else {
        SetStatus(s, "Task list is full (%d max)", kMaxTasks);
    }
}

static void DuplicateTask(ClayWidgets_Context &ui, DemoState &s, int32_t index) {
    if (index < 0 || index >= s.taskCount) {
        return;
    }
    char copyTitle[kTaskTitleCap];
    std::snprintf(copyTitle, sizeof(copyTitle), "%s (copy)", s.tasks[index].title);
    if (AddTask(s, copyTitle, s.tasks[index].priority)) {
        s.selectedTask = s.taskCount - 1;
        SetStatus(s, "Duplicated: %s", s.tasks[index].title);
        Notify(ui, s, CLAY_STRING("Task duplicated"), CLAY_WIDGETS_BADGE_ACCENT, 2.5f);
    } else {
        SetStatus(s, "Task list is full (%d max)", kMaxTasks);
    }
}

static void RequestDeleteTask(DemoState &s, int32_t index) {
    if (s.taskCount <= 0) {
        SetStatus(s, "No tasks to delete");
        return;
    }
    s.deleteTarget = (index >= 0 && index < s.taskCount) ? index : s.selectedTask;
    s.showDeleteModal = true;
}

// ---------------------------------------------------------------------------
// Chrome: header, menu bar, navigation, status bar
// ---------------------------------------------------------------------------

static void DrawHeader(ClayWidgets_Context &ui, DemoState &s, bool compactLayout) {
    CLAY(CLAY_ID("Header"), {
        .layout = {
            .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
            .childGap = ui.theme.spacing.md,
            .childAlignment = { .x = CLAY_ALIGN_X_LEFT, .y = CLAY_ALIGN_Y_CENTER },
            .layoutDirection = CLAY_LEFT_TO_RIGHT,
        },
    }) {
        ClayWidgets_Heading(&ui, CLAY_STRING("clay-widgets"));
        ClayWidgets_Badge(&ui, CLAY_STRING("demo"), CLAY_WIDGETS_BADGE_ACCENT);

        CLAY(CLAY_ID("HeaderSpacer"), {
            .layout = {
                .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIXED(1) },
            },
        }) {}

        // Quick theme switcher; the Settings page has the same state as radios.
        if (!compactLayout) {
            int32_t themeIndex = s.themePreset - 1;
            if (themeIndex < 0) themeIndex = 0;
            if (themeIndex > 3) themeIndex = 3;
            if (ClayWidgets_Segmented(&ui, CLAY_ID("HeaderThemeSeg"), kThemeNames, 4, &themeIndex)) {
                SetStatus(s, "Theme: %s", kThemeNames[themeIndex].chars);
            }
            s.themePreset = themeIndex + 1;
            ClayWidgets_Tooltip(&ui, CLAY_ID("HeaderThemeSeg"), CLAY_STRING("Restyle every widget instantly"));
        }
    }
}

static void DrawMenuBar(ClayWidgets_Context &ui, DemoState &s) {
    CLAY(CLAY_ID("MenuBar"), {
        .layout = {
            .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
            .padding = CLAY_PADDING_ALL(ui.theme.spacing.xs),
            .childGap = ui.theme.spacing.xs,
            .childAlignment = { .x = CLAY_ALIGN_X_LEFT, .y = CLAY_ALIGN_Y_CENTER },
            .layoutDirection = CLAY_LEFT_TO_RIGHT,
        },
        .backgroundColor = ui.theme.surfaceAltColor,
        .cornerRadius = CLAY_CORNER_RADIUS(ui.theme.radiusSm),
    }) {
        if (ClayWidgets_BeginMenu(&ui, CLAY_ID("FileMenu"), CLAY_STRING("File"))) {
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("MenuNewTask"), CLAY_STRING("New Sample Task"))) {
                AddSampleTask(ui, s);
            }
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("MenuReset"), CLAY_STRING("Reset Demo"))) {
                s.pendingReset = true;
                Notify(ui, s, CLAY_STRING("Demo reset"), CLAY_WIDGETS_BADGE_NEUTRAL, 2.5f);
            }
            ClayWidgets_MenuSeparator(&ui);
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("MenuDeleteTask"), CLAY_STRING("Delete Task..."))) {
                RequestDeleteTask(s, s.selectedTask);
            }
            ClayWidgets_EndMenu(&ui, CLAY_ID("FileMenu"));
        }

        if (ClayWidgets_BeginMenu(&ui, CLAY_ID("EditMenu"), CLAY_STRING("Edit"))) {
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("MenuUndo"), CLAY_STRING("Undo"))) {
                SetStatus(s, "Menu: Undo");
            }
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("MenuRedo"), CLAY_STRING("Redo"))) {
                SetStatus(s, "Menu: Redo");
            }
            ClayWidgets_EndMenu(&ui, CLAY_ID("EditMenu"));
        }

        if (ClayWidgets_BeginMenu(&ui, CLAY_ID("ViewMenu"), CLAY_STRING("View"))) {
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("MenuViewDashboard"), CLAY_STRING("Dashboard"))) {
                s.activeView = kViewDashboard;
            }
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("MenuViewTasks"), CLAY_STRING("Tasks"))) {
                s.activeView = kViewTasks;
            }
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("MenuViewGallery"), CLAY_STRING("Gallery"))) {
                s.activeView = kViewGallery;
            }
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("MenuViewSettings"), CLAY_STRING("Settings"))) {
                s.activeView = kViewSettings;
            }
            ClayWidgets_EndMenu(&ui, CLAY_ID("ViewMenu"));
        }
    }
}

static void DrawNavBar(ClayWidgets_Context &ui, DemoState &s) {
    CLAY(CLAY_ID("NavBar"), {
        .layout = {
            .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
            .childGap = 10,
            .layoutDirection = CLAY_LEFT_TO_RIGHT,
        },
    }) {
        ClayWidgets_Tab(&ui, CLAY_ID("NavDashboard"), CLAY_STRING("Dashboard"), kViewDashboard, &s.activeView);
        ClayWidgets_Tab(&ui, CLAY_ID("NavTasks"), CLAY_STRING("Tasks"), kViewTasks, &s.activeView);
        ClayWidgets_Tab(&ui, CLAY_ID("NavGallery"), CLAY_STRING("Gallery"), kViewGallery, &s.activeView);
        ClayWidgets_Tab(&ui, CLAY_ID("NavSettings"), CLAY_STRING("Settings"), kViewSettings, &s.activeView);

        ClayWidgets_Tooltip(&ui, CLAY_ID("NavDashboard"), CLAY_STRING("Live stats, a data table and quick actions"));
        ClayWidgets_Tooltip(&ui, CLAY_ID("NavTasks"), CLAY_STRING("A working to-do manager built from the kit"));
        ClayWidgets_Tooltip(&ui, CLAY_ID("NavGallery"), CLAY_STRING("The full widget catalog"));
        ClayWidgets_Tooltip(&ui, CLAY_ID("NavSettings"), CLAY_STRING("Theme, behavior and diagnostics"));
    }
}

static void DrawStatusBar(ClayWidgets_Context &ui, DemoState &s) {
    CLAY(CLAY_ID("StatusBar"), {
        .layout = {
            .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
            .padding = {
                .left = ui.theme.spacing.md,
                .right = ui.theme.spacing.md,
                .top = ui.theme.spacing.xs,
                .bottom = ui.theme.spacing.xs,
            },
            .childGap = ui.theme.spacing.md,
            .childAlignment = { .x = CLAY_ALIGN_X_LEFT, .y = CLAY_ALIGN_Y_CENTER },
            .layoutDirection = CLAY_LEFT_TO_RIGHT,
        },
        .backgroundColor = ui.theme.surfaceAltColor,
        .cornerRadius = CLAY_CORNER_RADIUS(ui.theme.radiusSm),
    }) {
        ClayWidgets_Label(&ui, ClayStringFromCString(s.statusLine));

        CLAY(CLAY_ID("StatusSpacer"), {
            .layout = {
                .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIXED(1) },
            },
        }) {}

        MutedLabel(ui, FormatString(s, "focus %u  |  %d fps", ui.focusedId, GetFPS()));
    }
}

// ---------------------------------------------------------------------------
// Dashboard view
// ---------------------------------------------------------------------------

// Stat cards grow on both axes so every card in the row matches the tallest
// one (the progress card); with FIT heights each card would hug its own
// content and the row would render as mismatched boxes. In the compact
// (stacked) layout the row is FIT, so GROW leaves heights at their natural
// content size.
static void StatCard(ClayWidgets_Context &ui, Clay_ElementId id, Clay_String value, Clay_String caption) {
    ClayWidgets_BeginCardEx(&ui, id, Clay_String{}, CLAY_SIZING_GROW(0), CLAY_SIZING_GROW(0));
    CLAY_TEXT(value, {
        .textColor = ui.theme.textColor,
        .fontId = ui.theme.fontHeading,
        .fontSize = static_cast<uint16_t>(ui.theme.fontSizeHeading + 6),
    });
    MutedLabel(ui, caption);
    ClayWidgets_EndCard(&ui, id);
}

static void DrawDashboardView(ClayWidgets_Context &ui, DemoState &s, bool compactLayout) {
    int32_t doneCount = CountCompletedTasks(s);
    int32_t openCount = s.taskCount - doneCount;
    float completion = s.taskCount > 0 ? static_cast<float>(doneCount) / static_cast<float>(s.taskCount) : 0.0f;

    ClayWidgets_BeginScrollPanel(&ui, CLAY_ID("DashboardPanel"),
        ClayWidgets_ScrollPanelOptions{ CLAY_SIZING_GROW(0), CLAY_SIZING_GROW(0), 0, 0, ui.theme.spacing.md });
    {
        CLAY(CLAY_ID("StatRow"), {
            .layout = {
                .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                .childGap = ui.theme.spacing.md,
                .layoutDirection = compactLayout ? CLAY_TOP_TO_BOTTOM : CLAY_LEFT_TO_RIGHT,
            },
        }) {
            StatCard(ui, CLAY_ID("StatOpen"), FormatString(s, "%d", openCount), CLAY_STRING("open tasks"));
            StatCard(ui, CLAY_ID("StatDone"), FormatString(s, "%d", doneCount), CLAY_STRING("completed"));

            ClayWidgets_BeginCardEx(&ui, CLAY_ID("StatProgress"), Clay_String{}, CLAY_SIZING_GROW(0), CLAY_SIZING_GROW(0));
            CLAY_TEXT(FormatString(s, "%d%%", static_cast<int>(std::lround(completion * 100.0f))), {
                .textColor = ui.theme.textColor,
                .fontId = ui.theme.fontHeading,
                .fontSize = static_cast<uint16_t>(ui.theme.fontSizeHeading + 6),
            });
            ClayWidgets_ProgressBar(&ui, CLAY_ID("DashProgress"), completion, CLAY_STRING("Completion"));
            ClayWidgets_EndCard(&ui, CLAY_ID("StatProgress"));
        }

        ClayWidgets_BeginCard(&ui, CLAY_ID("WelcomeCard"), CLAY_STRING("Welcome"));
        {
            ClayWidgets_Label(&ui, CLAY_STRING(
                "clay-widgets is a small immediate-mode widget kit built on Clay's layout engine, rendered here with raylib. "
                "Every frame this whole interface is rebuilt from plain structs - there is no retained widget tree to keep in sync.\n"
                "\n"
                "The Tasks view is a tiny working app built from the kit, the Gallery catalogs every widget, and Settings changes "
                "how the demo itself looks and behaves."));
            MutedLabel(ui, CLAY_STRING("Tab / Shift+Tab move focus, Enter activates, Escape dismisses. Right-click task rows for a context menu."));
            CLAY(CLAY_ID("WelcomeBadges"), {
                .layout = {
                    .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                    .childGap = ui.theme.spacing.sm,
                    .childAlignment = { .x = CLAY_ALIGN_X_LEFT, .y = CLAY_ALIGN_Y_CENTER },
                    .layoutDirection = CLAY_LEFT_TO_RIGHT,
                },
            }) {
                ClayWidgets_Badge(&ui, CLAY_STRING("immediate mode"), CLAY_WIDGETS_BADGE_ACCENT);
                ClayWidgets_Badge(&ui, CLAY_STRING("keyboard navigable"), CLAY_WIDGETS_BADGE_SUCCESS);
                ClayWidgets_Badge(&ui, CLAY_STRING("4 theme presets"), CLAY_WIDGETS_BADGE_NEUTRAL);
                ClayWidgets_Badge(&ui, CLAY_STRING("runs on web"), CLAY_WIDGETS_BADGE_WARNING);
            }
        }
        ClayWidgets_EndCard(&ui, CLAY_ID("WelcomeCard"));

        ClayWidgets_BeginCard(&ui, CLAY_ID("BuildsCard"), CLAY_STRING("Recent builds"));
        {
            ClayWidgets_TableColumn buildCols[] = {
                { CLAY_STRING("Pipeline"), CLAY_SIZING_GROW(0) },
                { CLAY_STRING("Status"), CLAY_SIZING_FIXED(110) },
                { CLAY_STRING("Duration"), CLAY_SIZING_FIXED(100) },
            };
            ClayWidgets_BeginTable(&ui, CLAY_ID("BuildsTable"), buildCols, 3);
            for (int32_t r = 0; r < kBuildRowCount; ++r) {
                Clay_ElementId rowId = Clay_GetElementIdWithIndex(CLAY_STRING("BuildRow"), static_cast<uint32_t>(r));
                Clay_String cells[] = { kBuildNames[r], kBuildStates[r], kBuildTimes[r] };
                if (ClayWidgets_TableRow(&ui, rowId, cells, 3, r, r == s.selectedBuild)) {
                    s.selectedBuild = r;
                    SetStatus(s, "Selected build: %.*s", static_cast<int>(kBuildNames[r].length), kBuildNames[r].chars);
                }
            }
            ClayWidgets_EndTable(&ui, CLAY_ID("BuildsTable"));

            CLAY(CLAY_ID("BuildLegend"), {
                .layout = {
                    .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                    .childGap = ui.theme.spacing.sm,
                    .childAlignment = { .x = CLAY_ALIGN_X_LEFT, .y = CLAY_ALIGN_Y_CENTER },
                    .layoutDirection = CLAY_LEFT_TO_RIGHT,
                },
            }) {
                ClayWidgets_Badge(&ui, CLAY_STRING("passing"), CLAY_WIDGETS_BADGE_SUCCESS);
                ClayWidgets_Badge(&ui, CLAY_STRING("flaky"), CLAY_WIDGETS_BADGE_WARNING);
                ClayWidgets_Badge(&ui, CLAY_STRING("broken"), CLAY_WIDGETS_BADGE_DANGER);
            }
        }
        ClayWidgets_EndCard(&ui, CLAY_ID("BuildsCard"));

        ClayWidgets_BeginCard(&ui, CLAY_ID("ActionsCard"), CLAY_STRING("Quick actions"));
        {
            CLAY(CLAY_ID("ActionsRow"), {
                .layout = {
                    .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                    .childGap = ui.theme.spacing.sm,
                    .layoutDirection = compactLayout ? CLAY_TOP_TO_BOTTOM : CLAY_LEFT_TO_RIGHT,
                },
            }) {
                if (ClayWidgets_ButtonEx(&ui, CLAY_ID("ActionAddTask"), CLAY_STRING("Add Sample Task"),
                        ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_PRIMARY, false})) {
                    AddSampleTask(ui, s);
                }
                if (ClayWidgets_Button(&ui, CLAY_ID("ActionToast"), CLAY_STRING("Show a Toast"))) {
                    SetStatus(s, "Toast requested");
                    Notify(ui, s, CLAY_STRING("Toasts float above every view"), CLAY_WIDGETS_BADGE_ACCENT, 3.0f);
                }
                if (ClayWidgets_ButtonEx(&ui, CLAY_ID("ActionClearDone"), CLAY_STRING("Clear Completed"),
                        ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_DANGER, false})) {
                    if (doneCount > 0) {
                        s.pendingClearCompleted = true;
                        SetStatus(s, "Cleared %d completed task(s)", doneCount);
                        Notify(ui, s, CLAY_STRING("Completed tasks cleared"), CLAY_WIDGETS_BADGE_DANGER, 2.5f);
                    } else {
                        SetStatus(s, "Nothing to clear");
                    }
                }
                ClayWidgets_ButtonEx(&ui, CLAY_ID("ActionDeploy"), CLAY_STRING("Deploy"),
                    ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_DEFAULT, true});
            }
            MutedLabel(ui, CLAY_STRING("The last button is disabled: inert, muted, and skipped by Tab."));
        }
        ClayWidgets_EndCard(&ui, CLAY_ID("ActionsCard"));
    }
    ClayWidgets_EndScrollPanel(&ui, CLAY_ID("DashboardPanel"));
}

// ---------------------------------------------------------------------------
// Tasks view
// ---------------------------------------------------------------------------

static void DrawTasksView(ClayWidgets_Context &ui, DemoState &s, bool compactLayout) {
    Clay_SizingAxis listWidth = compactLayout ? CLAY_SIZING_GROW(0) : CLAY_SIZING_PERCENT(0.58f);
    Clay_SizingAxis listHeight = compactLayout ? CLAY_SIZING_PERCENT(0.55f) : CLAY_SIZING_GROW(0);
    Clay_SizingAxis detailWidth = compactLayout ? CLAY_SIZING_GROW(0) : CLAY_SIZING_PERCENT(0.42f);

    CLAY(CLAY_ID("TasksColumns"), {
        .layout = {
            .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_GROW(0) },
            .childGap = 16,
            .layoutDirection = compactLayout ? CLAY_TOP_TO_BOTTOM : CLAY_LEFT_TO_RIGHT,
        },
    }) {
        CLAY(CLAY_ID("TaskListColumn"), {
            .layout = {
                .sizing = { .width = listWidth, .height = listHeight },
                .childGap = ui.theme.spacing.sm,
                .layoutDirection = CLAY_TOP_TO_BOTTOM,
            },
        }) {
            // --- Add form -------------------------------------------------
            // clearOnEnter empties the buffer inside the widget, so snapshot the
            // text first: Enter + now-empty buffer means "submitted".
            Clay_ElementId addInputId = CLAY_ID("NewTaskInput");
            char pendingTitle[kTaskTitleCap];
            std::snprintf(pendingTitle, sizeof(pendingTitle), "%s", s.newTaskTitle);

            ClayWidgets_TextInput(&ui, addInputId, CLAY_STRING("Add a task"),
                s.newTaskTitle, static_cast<int32_t>(sizeof(s.newTaskTitle)),
                ClayWidgets_TextInputOptions{"What needs doing? Press Enter to add", true});
            bool enterAdd = ui.input.keyEnter && ui.focusedId == addInputId.id
                && pendingTitle[0] != '\0' && s.newTaskTitle[0] == '\0';

            bool buttonAdd = false;
            CLAY(CLAY_ID("AddTaskRow"), {
                .layout = {
                    .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                    .childGap = ui.theme.spacing.sm,
                    .childAlignment = { .x = CLAY_ALIGN_X_LEFT, .y = CLAY_ALIGN_Y_BOTTOM },
                    .layoutDirection = CLAY_LEFT_TO_RIGHT,
                },
            }) {
                ClayWidgets_Combo(&ui, CLAY_ID("NewTaskPriority"), CLAY_STRING("Priority"),
                    kPriorityNames, 3, &s.newTaskPriority);
                buttonAdd = ClayWidgets_ButtonEx(&ui, CLAY_ID("AddTaskButton"), CLAY_STRING("Add Task"),
                    ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_PRIMARY, false});
            }

            const char *titleToAdd = nullptr;
            if (enterAdd) {
                titleToAdd = pendingTitle;
            } else if (buttonAdd && s.newTaskTitle[0] != '\0') {
                titleToAdd = s.newTaskTitle;
            }
            if (titleToAdd) {
                if (AddTask(s, titleToAdd, s.newTaskPriority)) {
                    s.selectedTask = s.taskCount - 1;
                    SetStatus(s, "Added: %s", s.tasks[s.taskCount - 1].title);
                    Notify(ui, s, CLAY_STRING("Task added"), CLAY_WIDGETS_BADGE_SUCCESS, 2.5f);
                } else {
                    SetStatus(s, "Task list is full (%d max)", kMaxTasks);
                }
                if (titleToAdd == s.newTaskTitle) {
                    s.newTaskTitle[0] = '\0';
                }
            }

            // --- Filter ---------------------------------------------------
            CLAY(CLAY_ID("TaskFilterRow"), {
                .layout = {
                    .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                    .childGap = ui.theme.spacing.sm,
                    .childAlignment = { .x = CLAY_ALIGN_X_LEFT, .y = CLAY_ALIGN_Y_CENTER },
                    .layoutDirection = CLAY_LEFT_TO_RIGHT,
                },
            }) {
                MutedLabel(ui, CLAY_STRING("Show"));
                ClayWidgets_Segmented(&ui, CLAY_ID("TaskFilter"), kTaskFilterNames, 3, &s.taskFilter);
            }

            // --- Task list (the new SelectRow widget) ----------------------
            int32_t shownCount = 0;
            ClayWidgets_BeginScrollPanel(&ui, CLAY_ID("TaskListPanel"),
                ClayWidgets_ScrollPanelOptions{ CLAY_SIZING_GROW(0), CLAY_SIZING_GROW(0), 0, 0, ui.theme.spacing.xs });
            {
                if (s.taskCount == 0) {
                    ClayWidgets_Label(&ui, CLAY_STRING("No tasks yet - add one above."));
                }
                for (int32_t i = 0; i < s.taskCount; ++i) {
                    DemoTask &t = s.tasks[i];
                    if (s.taskFilter == 1 && t.done) continue;
                    if (s.taskFilter == 2 && !t.done) continue;
                    ++shownCount;

                    Clay_ElementId rowId = Clay_GetElementIdWithIndex(CLAY_STRING("TaskRow"), static_cast<uint32_t>(i));
                    Clay_Color swatch = kPrioritySwatches[t.priority];
                    if (t.done) {
                        swatch.a = 96;
                    }
                    Clay_String trailing = t.done ? CLAY_STRING("done") : kPriorityNames[t.priority];

                    if (ClayWidgets_SelectRowEx(&ui, rowId, swatch, ClayStringFromCString(t.title), trailing, s.selectedTask == i)) {
                        s.selectedTask = i;
                        SetStatus(s, "Selected: %s", t.title);
                    }
                    if (ClayWidgets_RightClicked(&ui, rowId)) {
                        s.contextTask = i;
                        s.selectedTask = i;
                        ClayWidgets_OpenContextMenu(&ui, CLAY_ID("TaskMenu"), ui.input.mouseX, ui.input.mouseY);
                    }
                }
                if (s.taskCount > 0 && shownCount == 0) {
                    ClayWidgets_Label(&ui, CLAY_STRING("No tasks match this filter."));
                }
            }
            ClayWidgets_EndScrollPanel(&ui, CLAY_ID("TaskListPanel"));

            MutedLabel(ui, FormatString(s, "%d of %d tasks shown - right-click a row for actions", shownCount, s.taskCount));
        }

        // --- Detail editor: widgets bound straight into the task struct ----
        ClayWidgets_BeginScrollPanel(&ui, CLAY_ID("TaskDetailPanel"),
            ClayWidgets_ScrollPanelOptions{ detailWidth, CLAY_SIZING_GROW(0), 0, 0, ui.theme.spacing.md });
        {
            ClayWidgets_BeginCard(&ui, CLAY_ID("TaskDetailCard"), CLAY_STRING("Task details"));
            if (s.taskCount == 0) {
                ClayWidgets_Label(&ui, CLAY_STRING("Nothing selected - add a task on the left."));
            } else {
                DemoTask &t = s.tasks[s.selectedTask];

                ClayWidgets_TextInput(&ui, CLAY_ID("DetailTitle"), CLAY_STRING("Title"),
                    t.title, static_cast<int32_t>(sizeof(t.title)),
                    ClayWidgets_TextInputOptions{"Task title", false});

                ClayWidgets_Label(&ui, CLAY_STRING("Priority"));
                ClayWidgets_Radio(&ui, CLAY_ID("DetailPriorityHigh"), CLAY_STRING("High"), 0, &t.priority);
                ClayWidgets_Radio(&ui, CLAY_ID("DetailPriorityMedium"), CLAY_STRING("Medium"), 1, &t.priority);
                ClayWidgets_Radio(&ui, CLAY_ID("DetailPriorityLow"), CLAY_STRING("Low"), 2, &t.priority);

                ClayWidgets_Toggle(&ui, CLAY_ID("DetailDone"), CLAY_STRING("Completed"), &t.done);

                ClayWidgets_Separator(&ui);

                CLAY(CLAY_ID("DetailButtonRow"), {
                    .layout = {
                        .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                        .childGap = ui.theme.spacing.sm,
                        .layoutDirection = CLAY_LEFT_TO_RIGHT,
                    },
                }) {
                    if (ClayWidgets_Button(&ui, CLAY_ID("DetailDuplicate"), CLAY_STRING("Duplicate"))) {
                        DuplicateTask(ui, s, s.selectedTask);
                    }
                    if (ClayWidgets_ButtonEx(&ui, CLAY_ID("DetailDelete"), CLAY_STRING("Delete..."),
                            ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_DANGER, false})) {
                        RequestDeleteTask(s, s.selectedTask);
                    }
                }
                MutedLabel(ui, CLAY_STRING("Edits write straight into the task struct - the list on the left updates live."));
            }
            ClayWidgets_EndCard(&ui, CLAY_ID("TaskDetailCard"));
        }
        ClayWidgets_EndScrollPanel(&ui, CLAY_ID("TaskDetailPanel"));
    }
}

// ---------------------------------------------------------------------------
// Gallery view
// ---------------------------------------------------------------------------

static void DrawGalleryView(ClayWidgets_Context &ui, DemoState &s, DemoIcons &icons, bool compactLayout) {
    Clay_SizingAxis leftWidth = compactLayout ? CLAY_SIZING_GROW(0) : CLAY_SIZING_PERCENT(0.55f);
    Clay_SizingAxis leftHeight = compactLayout ? CLAY_SIZING_PERCENT(0.55f) : CLAY_SIZING_GROW(0);
    Clay_SizingAxis rightWidth = compactLayout ? CLAY_SIZING_GROW(0) : CLAY_SIZING_PERCENT(0.45f);

    CLAY(CLAY_ID("GalleryColumns"), {
        .layout = {
            .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_GROW(0) },
            .childGap = 16,
            .layoutDirection = compactLayout ? CLAY_TOP_TO_BOTTOM : CLAY_LEFT_TO_RIGHT,
        },
    }) {
        ClayWidgets_BeginScrollPanel(&ui, CLAY_ID("GalleryLeft"),
            ClayWidgets_ScrollPanelOptions{ leftWidth, leftHeight, 0, 0, ui.theme.spacing.md });
        {
            ClayWidgets_BeginCard(&ui, CLAY_ID("ButtonsCard"), CLAY_STRING("Buttons"));
            {
                MutedLabel(ui, CLAY_STRING("Four variants: default, primary (accent), danger, and disabled."));
                CLAY(CLAY_ID("GalleryButtonRow"), {
                    .layout = {
                        .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                        .childGap = ui.theme.spacing.sm,
                        .layoutDirection = compactLayout ? CLAY_TOP_TO_BOTTOM : CLAY_LEFT_TO_RIGHT,
                    },
                }) {
                    if (ClayWidgets_Button(&ui, CLAY_ID("GalleryDefault"), CLAY_STRING("Default"))) {
                        s.galleryClicks++;
                        SetStatus(s, "Default button clicked");
                    }
                    if (ClayWidgets_ButtonEx(&ui, CLAY_ID("GalleryPrimary"), CLAY_STRING("Primary"),
                            ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_PRIMARY, false})) {
                        s.galleryClicks++;
                        SetStatus(s, "Primary button clicked");
                    }
                    if (ClayWidgets_ButtonEx(&ui, CLAY_ID("GalleryDanger"), CLAY_STRING("Danger"),
                            ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_DANGER, false})) {
                        s.galleryClicks++;
                        SetStatus(s, "Danger button clicked");
                    }
                    ClayWidgets_ButtonEx(&ui, CLAY_ID("GalleryDisabled"), CLAY_STRING("Disabled"),
                        ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_DEFAULT, true});
                }
                ClayWidgets_Tooltip(&ui, CLAY_ID("GalleryPrimary"), CLAY_STRING("Accent-filled call to action"));
                ClayWidgets_Tooltip(&ui, CLAY_ID("GalleryDanger"), CLAY_STRING("For destructive actions"));
                MutedLabel(ui, FormatString(s, "Clicked %d time(s)", s.galleryClicks));
            }
            ClayWidgets_EndCard(&ui, CLAY_ID("ButtonsCard"));

            ClayWidgets_BeginCard(&ui, CLAY_ID("TextChoiceCard"), CLAY_STRING("Text & choice"));
            {
                ClayWidgets_TextInput(&ui, CLAY_ID("GalleryInput"), CLAY_STRING("Text input"),
                    s.galleryText, static_cast<int32_t>(sizeof(s.galleryText)),
                    ClayWidgets_TextInputOptions{"Selection, word jumps, Ctrl+A", false});
                ClayWidgets_Combo(&ui, CLAY_ID("GalleryCombo"), CLAY_STRING("Combo box"),
                    kBuildConfigNames, 4, &s.buildConfig);
                ClayWidgets_Label(&ui, CLAY_STRING("List box (click or focus + arrows)"));
                ClayWidgets_ListBox(&ui, CLAY_ID("GalleryListBox"), kChannelNames, 4, &s.channel);
            }
            ClayWidgets_EndCard(&ui, CLAY_ID("TextChoiceCard"));

            ClayWidgets_BeginCard(&ui, CLAY_ID("RangesCard"), CLAY_STRING("Ranges & numbers"));
            {
                ClayWidgets_Label(&ui, CLAY_STRING("Slider + progress bar"));
                s.volume = ClayWidgets_Slider(&ui, CLAY_ID("GalleryVolume"), s.volume,
                    ClayWidgets_SliderOptions{0.0f, 1.0f, 0.01f, true, 0});
                ClayWidgets_ProgressBar(&ui, CLAY_ID("GalleryVolumeBar"), s.volume,
                    FormatString(s, "Volume %d%%", static_cast<int>(std::lround(s.volume * 100.0f))));

                ClayWidgets_Label(&ui, CLAY_STRING("Stepper"));
                ClayWidgets_Stepper(&ui, CLAY_ID("GalleryRetry"), &s.retryCount,
                    ClayWidgets_StepperOptions{0, 10, 1});

                ClayWidgets_Label(&ui, CLAY_STRING("Segmented control"));
                ClayWidgets_Segmented(&ui, CLAY_ID("GalleryDensity"), kDensityNames, 3, &s.density);
            }
            ClayWidgets_EndCard(&ui, CLAY_ID("RangesCard"));

            ClayWidgets_BeginCard(&ui, CLAY_ID("TabsCard"), CLAY_STRING("Attached tabs"));
            {
                CLAY(CLAY_ID("MiniTabPlane"), {
                    .layout = {
                        .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                        .layoutDirection = CLAY_TOP_TO_BOTTOM,
                    },
                    .backgroundColor = ui.theme.surfaceColor,
                    .cornerRadius = CLAY_CORNER_RADIUS(ui.theme.radiusMd),
                    .border = {
                        .color = ui.theme.borderColor,
                        .width = { .left = 1, .right = 1, .top = 1, .bottom = 1 },
                    },
                }) {
                    CLAY(CLAY_ID("MiniTabStrip"), {
                        .layout = {
                            .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                            .padding = { .left = ui.theme.spacing.sm, .right = ui.theme.spacing.sm, .top = ui.theme.spacing.xs, .bottom = 0 },
                            .childGap = ui.theme.spacing.xs,
                            .layoutDirection = CLAY_LEFT_TO_RIGHT,
                        },
                    }) {
                        for (int32_t i = 0; i < kMiniTabCount; ++i) {
                            Clay_ElementId tabId = Clay_GetElementIdWithIndex(CLAY_STRING("MiniTab"), static_cast<uint32_t>(i));
                            ClayWidgets_TabEx(&ui, tabId, kMiniTabs[i].label, i, &s.miniTab, CLAY_WIDGETS_TAB_STYLE_ATTACHED);
                        }
                    }
                    CLAY(CLAY_ID("MiniTabBody"), {
                        .layout = {
                            .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                            .padding = CLAY_PADDING_ALL(ui.theme.spacing.md),
                            .childGap = ui.theme.spacing.sm,
                            .layoutDirection = CLAY_TOP_TO_BOTTOM,
                        },
                        .border = {
                            .color = ui.theme.borderColor,
                            .width = { .left = 0, .right = 0, .top = 1, .bottom = 0 },
                        },
                    }) {
                        int32_t page = (s.miniTab >= 0 && s.miniTab < kMiniTabCount) ? s.miniTab : 0;
                        ClayWidgets_Label(&ui, kMiniTabs[page].body);
                    }
                }
            }
            ClayWidgets_EndCard(&ui, CLAY_ID("TabsCard"));
        }
        ClayWidgets_EndScrollPanel(&ui, CLAY_ID("GalleryLeft"));

        ClayWidgets_BeginScrollPanel(&ui, CLAY_ID("GalleryRight"),
            ClayWidgets_ScrollPanelOptions{ rightWidth, CLAY_SIZING_GROW(0), 0, 0, ui.theme.spacing.md });
        {
            ClayWidgets_BeginCard(&ui, CLAY_ID("TogglesCard"), CLAY_STRING("Toggles & checks"));
            {
                ClayWidgets_Checkbox(&ui, CLAY_ID("GalleryAutosave"), CLAY_STRING("Autosave"), &s.autosave);
                ClayWidgets_Toggle(&ui, CLAY_ID("GalleryAutosaveToggle"), CLAY_STRING("Autosave (same state as above)"), &s.autosave);
                ClayWidgets_CheckboxEx(&ui, CLAY_ID("GalleryManaged"), CLAY_STRING("Telemetry (managed by policy)"), &s.telemetryLocked, true);

                ClayWidgets_Label(&ui, CLAY_STRING("Render quality"));
                ClayWidgets_Radio(&ui, CLAY_ID("GalleryQualityDraft"), CLAY_STRING("Draft"), 1, &s.quality);
                ClayWidgets_Radio(&ui, CLAY_ID("GalleryQualityBalanced"), CLAY_STRING("Balanced"), 2, &s.quality);
                ClayWidgets_Radio(&ui, CLAY_ID("GalleryQualityBest"), CLAY_STRING("Best"), 3, &s.quality);
            }
            ClayWidgets_EndCard(&ui, CLAY_ID("TogglesCard"));

            ClayWidgets_BeginCard(&ui, CLAY_ID("DataCard"), CLAY_STRING("Data display"));
            {
                ClayWidgets_Label(&ui, CLAY_STRING("Tree view"));
                if (ClayWidgets_TreeNode(&ui, CLAY_ID("TreeSrc"), CLAY_STRING("src"), 0, &s.treeSrcOpen)) {
                    if (ClayWidgets_TreeLeaf(&ui, CLAY_ID("TreeMain"), CLAY_STRING("main.cpp"), 1)) {
                        SetStatus(s, "Tree: main.cpp");
                    }
                    if (ClayWidgets_TreeNode(&ui, CLAY_ID("TreeWidgets"), CLAY_STRING("clay-widgets"), 1, &s.treeWidgetsOpen)) {
                        if (ClayWidgets_TreeLeaf(&ui, CLAY_ID("TreeButtonH"), CLAY_STRING("button.h"), 2)) {
                            SetStatus(s, "Tree: button.h");
                        }
                        if (ClayWidgets_TreeLeaf(&ui, CLAY_ID("TreeListRowH"), CLAY_STRING("list-row.h"), 2)) {
                            SetStatus(s, "Tree: list-row.h");
                        }
                        if (ClayWidgets_TreeLeaf(&ui, CLAY_ID("TreeWidgetsH"), CLAY_STRING("widgets.h"), 2)) {
                            SetStatus(s, "Tree: widgets.h");
                        }
                    }
                }
                if (ClayWidgets_TreeNode(&ui, CLAY_ID("TreeAssets"), CLAY_STRING("assets"), 0, &s.treeAssetsOpen)) {
                    if (ClayWidgets_TreeLeaf(&ui, CLAY_ID("TreeFont"), CLAY_STRING("Roboto-Regular.ttf"), 1)) {
                        SetStatus(s, "Tree: Roboto-Regular.ttf");
                    }
                }

                ClayWidgets_Separator(&ui);
                CLAY(CLAY_ID("IconRow"), {
                    .layout = {
                        .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                        .childGap = ui.theme.spacing.md,
                        .childAlignment = { .x = CLAY_ALIGN_X_LEFT, .y = CLAY_ALIGN_Y_CENTER },
                        .layoutDirection = CLAY_LEFT_TO_RIGHT,
                    },
                }) {
                    ClayWidgets_Icon(&ui, CLAY_ID("IconCheck"), &icons.check, 24, ui.theme.accentColor);
                    ClayWidgets_Icon(&ui, CLAY_ID("IconPlay"), &icons.play, 24, ui.theme.textColor);
                    ClayWidgets_Icon(&ui, CLAY_ID("IconCircle"), &icons.circle, 24, ui.theme.accentColor);
                    ClayWidgets_Icon(&ui, CLAY_ID("IconSquare"), &icons.square, 24, ui.theme.textMutedColor);
                    MutedLabel(ui, CLAY_STRING("Theme-tinted texture icons"));
                }

                CLAY(CLAY_ID("BadgeRow"), {
                    .layout = {
                        .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                        .childGap = ui.theme.spacing.sm,
                        .childAlignment = { .x = CLAY_ALIGN_X_LEFT, .y = CLAY_ALIGN_Y_CENTER },
                        .layoutDirection = CLAY_LEFT_TO_RIGHT,
                    },
                }) {
                    ClayWidgets_Badge(&ui, CLAY_STRING("Neutral"), CLAY_WIDGETS_BADGE_NEUTRAL);
                    ClayWidgets_Badge(&ui, CLAY_STRING("Accent"), CLAY_WIDGETS_BADGE_ACCENT);
                    ClayWidgets_Badge(&ui, CLAY_STRING("Success"), CLAY_WIDGETS_BADGE_SUCCESS);
                    ClayWidgets_Badge(&ui, CLAY_STRING("Warning"), CLAY_WIDGETS_BADGE_WARNING);
                    ClayWidgets_Badge(&ui, CLAY_STRING("Danger"), CLAY_WIDGETS_BADGE_DANGER);
                }
            }
            ClayWidgets_EndCard(&ui, CLAY_ID("DataCard"));

            ClayWidgets_BeginCard(&ui, CLAY_ID("OverlaysCard"), CLAY_STRING("Overlays"));
            {
                MutedLabel(ui, CLAY_STRING("Toasts, modal dialog, context menu and tooltips."));
                CLAY(CLAY_ID("ToastRow"), {
                    .layout = {
                        .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                        .childGap = ui.theme.spacing.sm,
                        .layoutDirection = compactLayout ? CLAY_TOP_TO_BOTTOM : CLAY_LEFT_TO_RIGHT,
                    },
                }) {
                    if (ClayWidgets_Button(&ui, CLAY_ID("ToastSuccess"), CLAY_STRING("Success toast"))) {
                        Notify(ui, s, CLAY_STRING("Saved successfully"), CLAY_WIDGETS_BADGE_SUCCESS, 2.5f);
                    }
                    if (ClayWidgets_Button(&ui, CLAY_ID("ToastWarning"), CLAY_STRING("Warning toast"))) {
                        Notify(ui, s, CLAY_STRING("Disk space is low"), CLAY_WIDGETS_BADGE_WARNING, 2.5f);
                    }
                    if (ClayWidgets_Button(&ui, CLAY_ID("ToastDanger"), CLAY_STRING("Danger toast"))) {
                        Notify(ui, s, CLAY_STRING("Connection lost"), CLAY_WIDGETS_BADGE_DANGER, 2.5f);
                    }
                }
                if (ClayWidgets_Button(&ui, CLAY_ID("GalleryOpenModal"), CLAY_STRING("Confirm dialog..."))) {
                    RequestDeleteTask(s, s.selectedTask);
                }

                CLAY(CLAY_ID("GalleryCtxTarget"), {
                    .layout = {
                        .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                        .padding = CLAY_PADDING_ALL(ui.theme.spacing.md),
                        .childAlignment = { .x = CLAY_ALIGN_X_CENTER, .y = CLAY_ALIGN_Y_CENTER },
                    },
                    .backgroundColor = ui.theme.surfaceColor,
                    .cornerRadius = CLAY_CORNER_RADIUS(ui.theme.radiusSm),
                    .border = {
                        .color = ui.theme.borderColor,
                        .width = { .left = 1, .right = 1, .top = 1, .bottom = 1 },
                    },
                }) {
                    ClayWidgets_Label(&ui, CLAY_STRING("Right-click here for a context menu"));
                }
                if (ClayWidgets_RightClicked(&ui, CLAY_ID("GalleryCtxTarget"))) {
                    ClayWidgets_OpenContextMenu(&ui, CLAY_ID("GalleryMenu"), ui.input.mouseX, ui.input.mouseY);
                }
            }
            ClayWidgets_EndCard(&ui, CLAY_ID("OverlaysCard"));
        }
        ClayWidgets_EndScrollPanel(&ui, CLAY_ID("GalleryRight"));
    }
}

// ---------------------------------------------------------------------------
// Settings view
// ---------------------------------------------------------------------------

static void DrawSettingsView(ClayWidgets_Context &ui, DemoState &s) {
    ClayWidgets_BeginScrollPanel(&ui, CLAY_ID("SettingsPanel"),
        ClayWidgets_ScrollPanelOptions{ CLAY_SIZING_GROW(0), CLAY_SIZING_GROW(0), 0, 0, ui.theme.spacing.md });
    {
        ClayWidgets_BeginCard(&ui, CLAY_ID("AppearanceCard"), CLAY_STRING("Appearance"));
        {
            ClayWidgets_Label(&ui, CLAY_STRING("Theme preset"));
            ClayWidgets_Radio(&ui, CLAY_ID("ThemeSlate"), CLAY_STRING("Slate"), CLAY_WIDGETS_THEME_PRESET_SLATE, &s.themePreset);
            ClayWidgets_Radio(&ui, CLAY_ID("ThemeSand"), CLAY_STRING("Sand"), CLAY_WIDGETS_THEME_PRESET_SAND, &s.themePreset);
            ClayWidgets_Radio(&ui, CLAY_ID("ThemeForest"), CLAY_STRING("Forest"), CLAY_WIDGETS_THEME_PRESET_FOREST, &s.themePreset);
            ClayWidgets_Radio(&ui, CLAY_ID("ThemeWin95"), CLAY_STRING("Windows"), CLAY_WIDGETS_THEME_PRESET_WIN95, &s.themePreset);

            ClayWidgets_Separator(&ui);
            ClayWidgets_Toggle(&ui, CLAY_ID("AnimToggle"), CLAY_STRING("Animate hover and state changes"), &s.animationsOn);
            MutedLabel(ui, CLAY_STRING("Also forced off by the --no-anim screenshot flag (reduce-motion support)."));
        }
        ClayWidgets_EndCard(&ui, CLAY_ID("AppearanceCard"));

        ClayWidgets_BeginCard(&ui, CLAY_ID("BehaviorCard"), CLAY_STRING("Behavior"));
        {
            if (ClayWidgets_Checkbox(&ui, CLAY_ID("NotificationsCheck"), CLAY_STRING("Show toast notifications"), &s.notifications)) {
                SetStatus(s, s.notifications ? "Notifications enabled" : "Notifications disabled");
                Notify(ui, s, CLAY_STRING("Notifications enabled"), CLAY_WIDGETS_BADGE_SUCCESS, 2.5f);
            }
            ClayWidgets_Combo(&ui, CLAY_ID("LogLevelCombo"), CLAY_STRING("Log level"), kLogLevelNames, 5, &s.logLevel);

            if (ClayWidgets_BeginCollapsible(&ui, CLAY_ID("AdvancedSection"), CLAY_STRING("Advanced options"), &s.showAdvanced)) {
                ClayWidgets_Checkbox(&ui, CLAY_ID("VerboseCheck"), CLAY_STRING("Verbose logging"), &s.verboseLogging);
                ClayWidgets_Checkbox(&ui, CLAY_ID("GpuCheck"), CLAY_STRING("Experimental GPU path"), &s.experimentalGpu);
                ClayWidgets_EndCollapsible(&ui, CLAY_ID("AdvancedSection"));
            }
        }
        ClayWidgets_EndCard(&ui, CLAY_ID("BehaviorCard"));

        ClayWidgets_BeginCard(&ui, CLAY_ID("DiagnosticsCard"), CLAY_STRING("Diagnostics"));
        {
            ClayWidgets_Label(&ui, FormatString(s, "Screen: %d x %d", GetScreenWidth(), GetScreenHeight()));
            ClayWidgets_Label(&ui, FormatString(s, "Pointer: %.0f, %.0f", ui.input.mouseX, ui.input.mouseY));
            ClayWidgets_Label(&ui, FormatString(s, "Focused widget id: %u", ui.focusedId));
            ClayWidgets_Label(&ui, FormatString(s, "Frame rate: %d fps", GetFPS()));
            ClayWidgets_Label(&ui, FormatString(s, "Animations: %s", ui.animationsEnabled ? "on" : "off"));

            ClayWidgets_Separator(&ui);
            if (ClayWidgets_ButtonEx(&ui, CLAY_ID("ResetDemoButton"), CLAY_STRING("Reset Demo State"),
                    ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_DANGER, false})) {
                s.pendingReset = true;
                Notify(ui, s, CLAY_STRING("Demo reset"), CLAY_WIDGETS_BADGE_NEUTRAL, 2.5f);
            }
        }
        ClayWidgets_EndCard(&ui, CLAY_ID("DiagnosticsCard"));

        ClayWidgets_BeginCard(&ui, CLAY_ID("AboutCard"), CLAY_STRING("About"));
        {
            ClayWidgets_Label(&ui, CLAY_STRING(
                "clay-widgets demo - a single-file example application for the clay-widgets immediate-mode UI kit.\n"
                "\n"
                "Bring your own renderer: the widgets only emit Clay render commands. This build draws them with raylib "
                "and compiles unchanged to WebAssembly."));
        }
        ClayWidgets_EndCard(&ui, CLAY_ID("AboutCard"));
    }
    ClayWidgets_EndScrollPanel(&ui, CLAY_ID("SettingsPanel"));
}

// ---------------------------------------------------------------------------
// Floating layers: context menus and the delete-confirmation modal.
// Declared at the root, after all views, so they overlay everything.
// ---------------------------------------------------------------------------

static void DrawFloatingLayers(ClayWidgets_Context &ui, DemoState &s) {
    if (ClayWidgets_BeginContextMenu(&ui, CLAY_ID("TaskMenu"))) {
        bool valid = s.contextTask >= 0 && s.contextTask < s.taskCount;
        if (valid) {
            DemoTask &t = s.tasks[s.contextTask];
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("TaskMenuToggle"),
                    t.done ? CLAY_STRING("Mark as active") : CLAY_STRING("Mark as done"))) {
                t.done = !t.done;
                SetStatus(s, "%s: %s", t.done ? "Completed" : "Reopened", t.title);
            }
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("TaskMenuDuplicate"), CLAY_STRING("Duplicate"))) {
                DuplicateTask(ui, s, s.contextTask);
            }
            ClayWidgets_MenuSeparator(&ui);
            if (ClayWidgets_MenuItem(&ui, CLAY_ID("TaskMenuDelete"), CLAY_STRING("Delete..."))) {
                RequestDeleteTask(s, s.contextTask);
            }
        } else {
            ClayWidgets_MenuItem(&ui, CLAY_ID("TaskMenuNone"), CLAY_STRING("(no task)"));
        }
        ClayWidgets_EndContextMenu(&ui, CLAY_ID("TaskMenu"));
    }

    if (ClayWidgets_BeginContextMenu(&ui, CLAY_ID("GalleryMenu"))) {
        if (ClayWidgets_MenuItem(&ui, CLAY_ID("CtxCut"), CLAY_STRING("Cut"))) {
            SetStatus(s, "Context: Cut");
        }
        if (ClayWidgets_MenuItem(&ui, CLAY_ID("CtxCopy"), CLAY_STRING("Copy"))) {
            SetStatus(s, "Context: Copy");
        }
        if (ClayWidgets_MenuItem(&ui, CLAY_ID("CtxPaste"), CLAY_STRING("Paste"))) {
            SetStatus(s, "Context: Paste");
        }
        ClayWidgets_MenuSeparator(&ui);
        if (ClayWidgets_MenuItem(&ui, CLAY_ID("CtxProps"), CLAY_STRING("Properties..."))) {
            SetStatus(s, "Context: Properties");
        }
        ClayWidgets_EndContextMenu(&ui, CLAY_ID("GalleryMenu"));
    }

    if (ClayWidgets_BeginModal(&ui, CLAY_ID("ConfirmDeleteModal"), CLAY_STRING("Delete task?"), &s.showDeleteModal)) {
        int32_t target = (s.deleteTarget >= 0 && s.deleteTarget < s.taskCount)
            ? s.deleteTarget
            : (s.taskCount > 0 ? s.selectedTask : -1);
        if (target >= 0 && target < s.taskCount) {
            ClayWidgets_Label(&ui, FormatString(s, "\"%s\" will be permanently removed.", s.tasks[target].title));
        } else {
            ClayWidgets_Label(&ui, CLAY_STRING("There is no task to delete."));
        }
        MutedLabel(ui, CLAY_STRING("The scrim dims and blocks everything behind this dialog until it is dismissed."));

        CLAY(CLAY_ID("ModalButtonRow"), {
            .layout = {
                .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_FIT(0, 0) },
                .childGap = ui.theme.spacing.sm,
                .childAlignment = { .x = CLAY_ALIGN_X_RIGHT, .y = CLAY_ALIGN_Y_CENTER },
                .layoutDirection = CLAY_LEFT_TO_RIGHT,
            },
        }) {
            if (ClayWidgets_Button(&ui, CLAY_ID("ModalCancel"), CLAY_STRING("Cancel"))) {
                s.showDeleteModal = false;
            }
            if (ClayWidgets_ButtonEx(&ui, CLAY_ID("ModalDelete"), CLAY_STRING("Delete"),
                    ClayWidgets_ButtonOptions{CLAY_WIDGETS_BUTTON_DANGER, target < 0})) {
                SetStatus(s, "Deleted: %s", s.tasks[target].title);
                s.pendingDelete = target;
                s.showDeleteModal = false;
                Notify(ui, s, CLAY_STRING("Task deleted"), CLAY_WIDGETS_BADGE_DANGER, 2.5f);
            }
        }

        ClayWidgets_EndModal(&ui, CLAY_ID("ConfirmDeleteModal"));
    }
}

} // namespace

int main(int argc, char **argv) {
    // Optional headless screenshot harness so the demo can be verified without a
    // human at the keyboard. Examples:
    //   clay-widgets-demo --shot out.png --view 0 --frames 3
    //   clay-widgets-demo --shot hover.png --mouse 400 300 --mousedown
    // When --shot is set the app renders `frames` frames (optionally injecting a
    // synthetic mouse position/press), writes a PNG, and exits.
    const char *shotPath = nullptr;
    int shotFrames = 3;
    int shotView = -1;
    float forceMouseX = -1.0f;
    float forceMouseY = -1.0f;
    bool forceMouseDown = false;
    float forceScrollY = 0.0f;
    int shotTheme = -1;
    bool shotOpenModal = false;
    // Optional second interaction phase (e.g. open a menu, then act on an item).
    float forceMouse2X = -1.0f;
    float forceMouse2Y = -1.0f;
    bool forceMouseDown2 = false;
    bool forceRightClick = false; // makes the phase-1 click a right-click
    bool shotToast = false;
    bool disableAnim = false; // --no-anim: snap all widget transitions for deterministic shots
    int screenWidth = 1080;   // --size W H: initial window size (shots at other layouts)
    int screenHeight = 720;
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--shot") == 0 && i + 1 < argc) {
            shotPath = argv[++i];
        } else if (std::strcmp(argv[i], "--frames") == 0 && i + 1 < argc) {
            shotFrames = std::atoi(argv[++i]);
        } else if (std::strcmp(argv[i], "--view") == 0 && i + 1 < argc) {
            shotView = std::atoi(argv[++i]);
        } else if (std::strcmp(argv[i], "--mouse") == 0 && i + 2 < argc) {
            forceMouseX = (float)std::atof(argv[++i]);
            forceMouseY = (float)std::atof(argv[++i]);
        } else if (std::strcmp(argv[i], "--mousedown") == 0) {
            forceMouseDown = true;
        } else if (std::strcmp(argv[i], "--scroll") == 0 && i + 1 < argc) {
            // per-frame vertical wheel delta injected under the synthetic mouse
            forceScrollY = (float)std::atof(argv[++i]);
        } else if (std::strcmp(argv[i], "--theme") == 0 && i + 1 < argc) {
            shotTheme = std::atoi(argv[++i]);
        } else if (std::strcmp(argv[i], "--openmodal") == 0) {
            shotOpenModal = true;
        } else if (std::strcmp(argv[i], "--mouse2") == 0 && i + 2 < argc) {
            forceMouse2X = (float)std::atof(argv[++i]);
            forceMouse2Y = (float)std::atof(argv[++i]);
        } else if (std::strcmp(argv[i], "--mousedown2") == 0) {
            forceMouseDown2 = true;
        } else if (std::strcmp(argv[i], "--rightclick") == 0) {
            forceRightClick = true;
        } else if (std::strcmp(argv[i], "--toast") == 0) {
            shotToast = true;
        } else if (std::strcmp(argv[i], "--no-anim") == 0) {
            disableAnim = true;
        } else if (std::strcmp(argv[i], "--size") == 0 && i + 2 < argc) {
            screenWidth = std::atoi(argv[++i]);
            screenHeight = std::atoi(argv[++i]);
        }
    }
    if (shotFrames < 1) {
        shotFrames = 1;
    }

    SetConfigFlags(FLAG_MSAA_4X_HINT | FLAG_VSYNC_HINT | FLAG_WINDOW_HIGHDPI | FLAG_WINDOW_RESIZABLE);
    InitWindow(screenWidth, screenHeight, "clay-widgets demo");
    SetTargetFPS(60);

    // If the platform/GL context could not be created (e.g. no display, a locked
    // or disconnected session), bail before touching the GPU so we exit cleanly
    // instead of crashing on the first texture upload.
    if (!IsWindowReady()) {
        TraceLog(LOG_ERROR, "Window/display unavailable; cannot start the demo.");
        return 2;
    }

#ifdef __EMSCRIPTEN__
    // Match the canvas to the browser window now, then on every window resize,
    // so the layout fills the page and reflows (e.g. collapses to one column on
    // narrow windows) instead of staying pinned to the initial 1080x720.
    ClayWidgets_SyncCanvasToWindow();
    emscripten_set_resize_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, nullptr, EM_FALSE, ClayWidgets_OnResize);
#endif

    // raylib's HighDPI path multiplies every draw by GetWindowScaleDPI(), so a
    // glyph drawn at logical size S covers S*dpi device pixels. The font cache
    // bakes each atlas at that physical size (and we draw with the logical size),
    // so glyphs sample 1:1 on screen at any DPI.
    Vector2 dpiScale = GetWindowScaleDPI();

    // The UI font is baked into the binary (embedded_font.h), so there are no
    // external asset files. FontCache bakes one gamma-corrected atlas per pixel
    // size the UI asks for instead of scaling a single baked bitmap.
    FontCache fontCache;
    fontCache.dpiScale = std::max(dpiScale.x, dpiScale.y);
    fontCache.fallback = GetFontDefault();
    {
        // Probe once at the body size: fail loudly (and fall back to the default
        // font) if the embedded bytes are bad, and warm the most-used size. The
        // other sizes bake lazily on first use.
        int probeSize = FontCache_PixelSize(fontCache, 16.0f);
        Font probe = ClayWidgets_BakeFont(kEmbeddedRobotoTTF, static_cast<int>(kEmbeddedRobotoTTFSize), probeSize);
        if (probe.texture.id != 0) {
            SetTextureFilter(probe.texture, TEXTURE_FILTER_BILINEAR);
            fontCache.haveEmbedded = true;
            fontCache.atlases.emplace_back(probeSize, probe);
        } else {
            TraceLog(LOG_WARNING, "Failed to decode embedded font. Using default font.");
        }
    }

    // Procedurally generated white glyph textures used to demonstrate the image
    // element. Drawing them white lets ClayWidgets_Icon recolor them per theme
    // via its tint. Passed to the widgets as opaque Texture2D* handles.
    DemoIcons icons = {};
    {
        Image im = GenImageColor(64, 64, BLANK);
        ImageDrawLineEx(&im, Vector2{14, 34}, Vector2{27, 47}, 7, WHITE);
        ImageDrawLineEx(&im, Vector2{27, 47}, Vector2{52, 16}, 7, WHITE);
        icons.check = LoadTextureFromImage(im);
        UnloadImage(im);
    }
    {
        Image im = GenImageColor(64, 64, BLANK);
        ImageDrawTriangle(&im, Vector2{22, 14}, Vector2{22, 50}, Vector2{52, 32}, WHITE);
        icons.play = LoadTextureFromImage(im);
        UnloadImage(im);
    }
    {
        Image im = GenImageColor(64, 64, BLANK);
        ImageDrawCircle(&im, 32, 32, 20, WHITE);
        icons.circle = LoadTextureFromImage(im);
        UnloadImage(im);
    }
    {
        Image im = GenImageColor(64, 64, BLANK);
        ImageDrawRectangle(&im, 14, 14, 36, 36, WHITE);
        icons.square = LoadTextureFromImage(im);
        UnloadImage(im);
    }
    SetTextureFilter(icons.check, TEXTURE_FILTER_BILINEAR);
    SetTextureFilter(icons.play, TEXTURE_FILTER_BILINEAR);
    SetTextureFilter(icons.circle, TEXTURE_FILTER_BILINEAR);
    SetTextureFilter(icons.square, TEXTURE_FILTER_BILINEAR);

    uint32_t clayMemorySize = Clay_MinMemorySize();
    void *clayMemory = std::malloc(clayMemorySize);
    if (!clayMemory) {
        TraceLog(LOG_ERROR, "Failed to allocate Clay arena");
        CloseWindow();
        return 1;
    }

    Clay_Arena arena = Clay_CreateArenaWithCapacityAndMemory(clayMemorySize, clayMemory);
    Clay_Initialize(arena, Clay_Dimensions{static_cast<float>(screenWidth), static_cast<float>(screenHeight)}, Clay_ErrorHandler{HandleClayError, 0});
    //Clay_SetDebugModeEnabled(true);
    Clay_SetMeasureTextFunction(MeasureTextRaylib, &fontCache);

    ClayWidgets_Context ui = {};
    ClayWidgets_Theme theme = ClayWidgets_DefaultTheme();
    ClayWidgets_Init(&ui, theme);
    ClayWidgets_SetMeasureTextFunction(&ui, MeasureTextRaylib, &fontCache);

    DemoState demo;
    SeedTasks(demo);

    if (shotView >= kViewDashboard && shotView <= kViewSettings) {
        demo.activeView = shotView;
    }
    if (shotTheme >= 1) {
        demo.themePreset = shotTheme;
    }
    if (shotOpenModal) {
        demo.showDeleteModal = true;
    }
    if (shotToast) {
        ClayWidgets_ShowToast(&ui, CLAY_STRING("Changes applied"), CLAY_WIDGETS_BADGE_SUCCESS, 6.0f);
    }
    int shotFrameCounter = 0;

    bool webQuit = false;
    auto frameStep = [&]() {
        float dt = GetFrameTime();

        demo.scratchUsed = 0;
        ApplyPendingTaskEdits(demo);

        char frameUtf8[64] = {};
        int frameUtf8Len = 0;
        for (;;) {
            int codepoint = GetCharPressed();
            if (codepoint == 0) {
                break;
            }
            AppendUtf8FromCodepoint(frameUtf8, frameUtf8Len, static_cast<int>(sizeof(frameUtf8) - 1), codepoint);
        }
        frameUtf8[frameUtf8Len] = '\0';

        ClayWidgets_Input input = {};
        input.mouseX = static_cast<float>(GetMouseX());
        input.mouseY = static_cast<float>(GetMouseY());
        input.pointerDown = IsMouseButtonDown(MOUSE_BUTTON_LEFT);
        input.pointerPressed = IsMouseButtonPressed(MOUSE_BUTTON_LEFT);
        input.pointerReleased = IsMouseButtonReleased(MOUSE_BUTTON_LEFT);
        input.pointerRightPressed = IsMouseButtonPressed(MOUSE_BUTTON_RIGHT);
        Vector2 wheel = GetMouseWheelMoveV();
        input.scrollX = wheel.x;
        input.scrollY = wheel.y;
        input.deltaTime = dt;
        input.textUtf8 = frameUtf8;
        input.textUtf8Length = frameUtf8Len;
        input.keyBackspace = IsKeyPressed(KEY_BACKSPACE);
        input.keyDelete = IsKeyPressed(KEY_DELETE);
        input.keyHome = IsKeyPressed(KEY_HOME);
        input.keyEnd = IsKeyPressed(KEY_END);
        input.keyLeft = IsKeyPressed(KEY_LEFT);
        input.keyRight = IsKeyPressed(KEY_RIGHT);
        input.keyUp = IsKeyPressed(KEY_UP);
        input.keyDown = IsKeyPressed(KEY_DOWN);
        input.keyEnter = IsKeyPressed(KEY_ENTER);
        input.keyEscape = IsKeyPressed(KEY_ESCAPE);
        input.keyTab = IsKeyPressed(KEY_TAB);
        input.keySelectAll = (IsKeyDown(KEY_LEFT_CONTROL) || IsKeyDown(KEY_RIGHT_CONTROL)) && IsKeyPressed(KEY_A);
        input.shiftDown = IsKeyDown(KEY_LEFT_SHIFT) || IsKeyDown(KEY_RIGHT_SHIFT);

        // Screenshot harness: inject a synthetic pointer so hover/press states can
        // be captured. pointerPressed fires only on the first frame it is held.
        if (shotPath && forceMouseX >= 0.0f) {
            // Two scripted interaction phases so tests can, e.g., click to open a
            // menu (phase 1) and then act on an item (phase 2). Each "click" is a
            // press+release a couple frames after its phase begins, so target
            // elements (including floating popups) are laid out before the
            // pointer acts on them.
            bool phase2 = (forceMouse2X >= 0.0f) && (shotFrameCounter >= 4);
            input.mouseX = phase2 ? forceMouse2X : forceMouseX;
            input.mouseY = phase2 ? forceMouse2Y : forceMouseY;

            int clickFrame = phase2 ? 6 : 2;
            bool wantClick = phase2 ? forceMouseDown2 : forceMouseDown;
            bool press = wantClick && (shotFrameCounter == clickFrame);
            bool release = wantClick && (shotFrameCounter == clickFrame + 1);
            // A right-click is only scripted for phase 1 (e.g. open a context
            // menu), then phase 2 uses the left button to choose an item.
            bool rightClick = forceRightClick && !phase2;
            input.pointerDown = press && !rightClick;
            input.pointerPressed = press && !rightClick;
            input.pointerReleased = release && !rightClick;
            input.pointerRightPressed = press && rightClick;
        }
        if (shotPath && forceScrollY != 0.0f) {
            // Feed the wheel delta on every frame but the last, so the panel has
            // settled by the time the screenshot is taken.
            input.scrollY = (shotFrameCounter < shotFrames - 1) ? forceScrollY : 0.0f;
        }

        ui.theme = ClayWidgets_ThemeFromPreset((ClayWidgets_ThemePreset)demo.themePreset);
        ui.animationsEnabled = demo.animationsOn && !disableAnim;

        ClayWidgets_BeginFrame(
            &ui,
            input,
            Clay_Dimensions{static_cast<float>(GetScreenWidth()), static_cast<float>(GetScreenHeight())},
            true
        );

        bool compactLayout = GetScreenWidth() < 900;

        CLAY(CLAY_ID("Root"), {
            .layout = {
                .sizing = { .width = CLAY_SIZING_GROW(0), .height = CLAY_SIZING_GROW(0) },
                .padding = CLAY_PADDING_ALL(16),
                .childGap = 12,
                .layoutDirection = CLAY_TOP_TO_BOTTOM,
            },
            .backgroundColor = ui.theme.surfaceColor,
        }) {
            DrawHeader(ui, demo, compactLayout);
            DrawMenuBar(ui, demo);
            DrawNavBar(ui, demo);

            switch (demo.activeView) {
                case kViewTasks:
                    DrawTasksView(ui, demo, compactLayout);
                    break;
                case kViewGallery:
                    DrawGalleryView(ui, demo, icons, compactLayout);
                    break;
                case kViewSettings:
                    DrawSettingsView(ui, demo);
                    break;
                case kViewDashboard:
                default:
                    DrawDashboardView(ui, demo, compactLayout);
                    break;
            }

            DrawStatusBar(ui, demo);

            // Floating layers last so they overlay every view; the toast layer
            // floats above even those.
            DrawFloatingLayers(ui, demo);
            ClayWidgets_ToastLayer(&ui);
        }

        Clay_RenderCommandArray commands = ClayWidgets_EndFrame(dt);

        BeginDrawing();
        ClearBackground(Color{18, 20, 25, 255});
        RenderClayCommands(commands, fontCache);
        EndDrawing();

        if (shotPath) {
            if (++shotFrameCounter >= shotFrames) {
                TakeScreenshot(shotPath);
                webQuit = true;
                return;
            }
        }
    };

#ifdef __EMSCRIPTEN__
    // fps=0 => drive from requestAnimationFrame; simulate_infinite_loop=1 (with
    // -sASYNCIFY) suspends here without unwinding main()'s stack.
    g_webFrame = frameStep;
    emscripten_set_main_loop(ClayWidgets_WebFrame, 0, 1);
#else
    while (!WindowShouldClose() && !webQuit) {
        frameStep();
    }
#endif

    UnloadTexture(icons.check);
    UnloadTexture(icons.play);
    UnloadTexture(icons.circle);
    UnloadTexture(icons.square);
    FontCache_Unload(fontCache);
    std::free(clayMemory);
    CloseWindow();
    return 0;
}
