#!/usr/bin/env python3
"""Generate the single-file clay-widgets.h amalgam.

Inlines clay-widgets/*.h into one header in the exact order widgets.h
includes them, stripping each sub-header's include guard and its
"include widgets.h first" preamble. Everything else is preserved
byte-for-byte, including the CLAY_WIDGETS_IMPLEMENTATION sections, so the
amalgam behaves identically to the split tree: include it (with clay.h on
the include path) and define CLAY_WIDGETS_IMPLEMENTATION in exactly one
translation unit.

clay.h is deliberately NOT bundled - it is a separate library with its own
version and license; the amalgam keeps `#include "clay.h"` as its one
dependency.

The output is deterministic (no timestamps), so regenerating without source
changes produces an identical file. `make test-amalgam` compiles the full
unit-test suite against the generated header, which is what CI runs - an
incomplete or mis-ordered amalgam fails loudly rather than shipping.

Usage:
  python tools/amalgamate.py                      # writes build/clay-widgets.h
  python tools/amalgamate.py -o path/to/out.h
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WIDGETS_DIR = PROJECT_ROOT / "clay-widgets"
UMBRELLA = WIDGETS_DIR / "widgets.h"

INCLUDE_RE = re.compile(r'^#include\s+"([^"]+)"\s*$')

BANNER = """\
// clay-widgets.h - single-file amalgam of the clay-widgets library.
//
// GENERATED by tools/amalgamate.py from clay-widgets/*.h - DO NOT EDIT.
// Edit the split headers and regenerate with:  python tools/amalgamate.py
//
// Usage is identical to the split tree:
//   - clay.h must be on the include path (it is not bundled).
//   - In exactly one translation unit, define CLAY_WIDGETS_IMPLEMENTATION
//     before including this header.
"""


class AmalgamError(RuntimeError):
    pass


def strip_sub_header(name: str, text: str) -> str:
    """Remove a sub-header's include guard and its widgets.h-first preamble.

    Every clay-widgets sub-header follows the same shape; anything that
    deviates is an error so format drift breaks the build instead of
    silently corrupting the amalgam.
    """
    lines = text.splitlines()

    # Outer include guard: the first two non-blank lines.
    index = 0
    while index < len(lines) and not lines[index].strip():
        index += 1
    if index + 1 >= len(lines) or not lines[index].startswith("#ifndef CLAY_WIDGETS"):
        raise AmalgamError(f"{name}: expected '#ifndef CLAY_WIDGETS_..._H' include guard")
    guard = lines[index].split()[1]
    if not lines[index + 1].startswith(f"#define {guard}"):
        raise AmalgamError(f"{name}: expected '#define {guard}' after the guard")
    del lines[index : index + 2]

    # The "include widgets.h before me" preamble: a 3-line block.
    for start in range(len(lines)):
        if lines[start].strip() == "#ifndef CLAY_WIDGETS_H":
            if (
                start + 2 < len(lines)
                and lines[start + 1].lstrip().startswith("#error")
                and lines[start + 2].strip() == "#endif"
            ):
                del lines[start : start + 3]
                break
            raise AmalgamError(f"{name}: malformed widgets.h-first preamble")
    else:
        raise AmalgamError(f"{name}: missing '#ifndef CLAY_WIDGETS_H' preamble")

    # Closing '#endif' of the include guard: the last non-blank line.
    index = len(lines) - 1
    while index >= 0 and not lines[index].strip():
        index -= 1
    if index < 0 or lines[index].strip() != "#endif":
        raise AmalgamError(f"{name}: expected the file to end with the guard's '#endif'")
    del lines[index:]

    # Trim blank padding so the banners control the spacing.
    while lines and not lines[0].strip():
        del lines[0]
    while lines and not lines[-1].strip():
        del lines[-1]

    return "\n".join(lines)


def build_amalgam() -> str:
    umbrella_text = UMBRELLA.read_text(encoding="utf-8")
    out: list[str] = [BANNER]
    inlined: list[str] = []

    for line in umbrella_text.splitlines():
        match = INCLUDE_RE.match(line)
        sub_path = WIDGETS_DIR / match.group(1) if match else None
        if match and sub_path is not None and sub_path.exists():
            name = match.group(1)
            body = strip_sub_header(name, sub_path.read_text(encoding="utf-8"))
            rule = "-" * 75
            out.append(f"// {rule}\n// {name}\n// {rule}\n\n{body}\n")
            inlined.append(name)
        else:
            # Everything else (including '#include "clay.h"' - not ours to
            # bundle) passes through untouched.
            out.append(line)

    if not inlined:
        raise AmalgamError("widgets.h contained no inlinable clay-widgets includes")

    # Every header in the directory must have been pulled in via widgets.h;
    # a new widget file that was never added to the umbrella is a bug.
    all_headers = {p.name for p in WIDGETS_DIR.glob("*.h")} - {"widgets.h"}
    missed = sorted(all_headers - set(inlined))
    if missed:
        raise AmalgamError(f"headers not included by widgets.h: {', '.join(missed)}")

    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the single-file clay-widgets.h amalgam")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=PROJECT_ROOT / "build" / "clay-widgets.h",
        help="output path (default: build/clay-widgets.h)",
    )
    args = parser.parse_args()

    try:
        amalgam = build_amalgam()
    except AmalgamError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(amalgam, encoding="utf-8", newline="\n")
    line_count = amalgam.count("\n")
    print(f"wrote {args.output} ({line_count} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
